### ISSUE TITLE
Not able to press OK after pasting key.

### ISSUE THREAD

**Issue by Blom1974** [elupus/hass_nibe#1]
![image](https://user-images.githubusercontent.com/9973750/29487651-6174058c-84fd-11e7-995c-6c26f9637452.png)

**Comment by elupus** [comment]
![image](https://user-images.githubusercontent.com/482976/29635368-228f8f78-884d-11e7-9609-c9239b79f1ff.png)

This is how it should look. You don't see the set configuration button?

**Comment by elupus** [comment]
What version of home assistant?

**Comment by Blom1974** [comment]
Running HomeAssistant 0.51.2
Tested on Chrome Version 60.0.3112.101 (And other browsers)

**Comment by Blom1974** [comment]
Which version did you test on? Maybe i am able to rollback to that version. Activate and then upgrade.
Or is is some other way to manually enter it somewhere.

**Comment by elupus** [comment]
I'm running 0.51.2. So that should not be an issue. Have you tried doing a very clean home assistant config with pretty much only the nibe component? Could you do that and post the log. Also could be worth pulling up chrome developer screen and see for any website errors

**Comment by elupus** [comment]
Okey. I managed to reproduce it. I think it depends on window size of the browser

**Comment by Blom1974** [comment]
Thanks a lot! Verified working in my installation!
