### ISSUE TITLE
Ventilation 

### ISSUE THREAD

**Issue by jamiewalters** [elupus/hass_nibe#10]
I am interested in being able to change the ventilation fan speed, I managed to add this to a copy of this repo, however its not possible to say of I made it generic or specific to my pump. 

Was this something you looked at ?

**Comment by elupus** [comment]
Don't have anything like that. What did you change?

**Comment by elupus** [comment]
Could you show me the code? A pull request perhaps. I think adding it as a optional fan/ventilation component is best.

**Comment by elupus** [comment]
Cant you try to add it as a fan component? Should be mostly copy paste from sensor platform?

**Comment by jamiewalters** [comment]
Good idea, I'll check that out

**Comment by jamiewalters** [comment]
How does your fan setting look at home, can you freely change the settings or you have to select some preset levels. I have a F370 and I can only select some preset levels.

**Comment by elupus** [comment]
Mine doesnt have a fan. Its a ground heat pump

**Comment by jamiewalters** [comment]
ok, testing will then of course be limited to mine for the time being.

**Comment by jamiewalters** [comment]
Still looking at this, I have this theory that parameter ids are fixed by Nibe which means that eg., 40004 is always outdoor temp. I had a look at the website backend calls. Is this the case for your system?

**Comment by elupus** [comment]
https://github.com/elupus/nibeuplink/blob/e7d976e64df94c230a7ab15336db653ae2bf8bd9/src/nibeuplink/__init__.py#L40

**Comment by jamiewalters** [comment]
Exactly, ventilation then sounds easy to add as I fan, I can proceed with it. Perhaps the climate component could be simplified?

**Comment by elupus** [comment]
Not sure how it could be simplified?

**Comment by imist** [comment]
I have a F750 and is also interested in this. I guess a NIBE Uplink Premium subscription is needed in order to try this out, right?

**Comment by jamiewalters** [comment]
Yes, you need premium.

**Comment by elupus** [comment]
Did you have diff on your hack?

**Comment by stphndrnd** [comment]
Hey guys,

Just wondered if anyone has tried to get the full set of switches for the ventilation of Nibe pump? I.e. I have a F750, I can set the ventilation to 25%, 50%, 75% and 100%. Right now the ventilation boost switch sets it to 100% for a configured time but I am looking at being able to have a switch for each speed.

Possible?

Thanks!
/S

**Comment by elupus** [comment]
Fans can now be controlled by a fan entity. Closing for now.
