### ISSUE TITLE
Pre-set ventilation: "The speed 4 is not a valid speed"

### ISSUE THREAD

**Issue by PalmMx** [elupus/hass_nibe#100]
I manually increased the ventilation on my F750 tonight to 100 %, i.e. pre-set speed 4. After that I got errors in my log in Hass.
Running Hass 2021.7.4

Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 22:03:39 (112 occurrences)
Last logged: 23:59:03

Exception in async_parameters_updated when dispatching 'nibe.parameters_updated': (99999, {10001: {'parameterId': 10001, 'name': 'fan_speed', 'title': 'fan speed', 'designation': '', 'unit': '%', 'displayValue': '100%', 'rawValue': 100, 'value': 100.0}, 40025: {'parameterId': 40025, 'name': '40025', 'title': 'exhaust air', 'designation': 'BT20', 'unit': '°C', 'displayValue': '25.2°C', 'rawValue': 252, 'value': 25.2}, 40026: {'parameterId': 40026, 'name': '40026', 'title': 'extract air', 'designation': 'BT21', 'unit': '°C', 'displayValue': '23.6°C', 'rawValue': 236, 'value': 23.6}}) Traceback (most recent call last): File "/config/custom_components/nibe/entity.py", line 133, in async_parameters_updated self.async_schedule_update_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 576, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 455, in _async_write_ha_state attr.update(self.state_attributes or {}) File "/config/custom_components/nibe/fan.py", line 103, in state_attributes data = super().state_attributes File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 608, in state_attributes data[ATTR_PERCENTAGE] = self.percentage File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 469, in percentage return self.speed_to_percentage(self.speed) File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 553, in speed_to_percentage raise NotValidSpeedError(f"The speed {speed} is not a valid speed.") homeassistant.components.fan.NotValidSpeedError: The speed 4 is not a valid speed.

**Comment by elupus** [comment]
Oh right they have changed how speeds for fans work. The component need to be adjusted.

**Comment by ksvard** [comment]
FYI, I have the exact same problem. Would be nice to have the component updated. Unfortunately I do not have the programming skills to help out.
BR

**Comment by elupus** [comment]
Should be fixed now.

**Comment by ksvard** [comment]
Did the update today and it works fine. No more errors in the core log. Could be mentioned that the data after the update is available as attributes to the entity. This may need some minor changes in the users lovelace interface.
