### ISSUE TITLE
Cant set Fan/Ventilation speed

### ISSUE THREAD

**Issue by hnktnk** [elupus/hass_nibe#104]
Hi!

I've started looking at automations to run the fans more or less on different conditions but it seems as I cannot set the different presets any more. In the pump (F730) i have 4 presets, 0%, 30%, 55% and 100% (I think) but I can only set "auto" or "boost" in HA but I have no idea what values they actually have.

Is there anything I could change in the config or some other thing? Setting fan value in the automations setting gives me an error in the log. I'll make sure to send you a log snippet later on.

**Comment by elupus** [comment]
Those at the only accepted by nibe  API. You can't set anything else. You could obviously open a support issue with them to allow more.
