### ISSUE TITLE
Nibe F750 - Adjust "set temperature" 47398 (set value)

### ISSUE THREAD

**Issue by msandvold** [elupus/hass_nibe#107]
Hi, elupus.

First of all - GREAT WORK.

I have after several attempts reinstalled via HACS - setup as described in readme with vrite access.
Everything runs smootly, only one exeption. I cannot adjust the "set temperature" using the "thermostat" settings in configuration.yaml 
```
          name: 'Stue'
          current_temperature: [using tempsensor from a Firealarm or sensor.nibe_xxxxxx_40033 (Tempsensor indoor/BT50 room temp S1) 
          systems: 1
```

Settings Thermostat:
heat/cool as described - adjust temp from 22 to 23 - but no changes in the set temp for my F750.

Could You help me solve this case.

**Comment by elupus** [comment]
Have you enabled smart thermostats in your pump menus?

**Comment by msandvold** [comment]
I thought thar I have - will check again when I get home from work.
I will let you know.
Thx for the quick reply.

**Comment by msandvold** [comment]
Hi. Yes, smart i active.
Checked my Nibe uplink account, seems like Nibe supports IFTTT .com integration.
in the overview I can not find anything else...

Suggestions?

**Comment by msandvold** [comment]
Yes, heat/cool is Active.
Is there something else than this I need to put in config?

name: 'Stue'
          current_temperature: [using tempsensor from a Firealarm or sensor.nibe_xxxxxx_40033 (Tempsensor indoor/BT50 room temp S1) 
          systems: 1

?

**Comment by elupus** [comment]
If you head to nibeuplink.com and check under the smart thermostats page, are the temperatures from home assistant reported correctly?

**Comment by msandvold** [comment]
There is nothing under Thermostats (smart home)
I do not prosess any external Thermostat connected to F750, only one outdoor and one indoor  temp tempsensor. 
Do I need the RMU 40 unit?

i do have integrated Nibe with Tibber (not sure if You Are familier with that) - no problem adjusting the set temperatur from Tibber app. Also connected to nibeuplink, without any Thermostat connected.

**Comment by msandvold** [comment]
Hi.
Do You know what the solution may be, or if it is possible to control temp settings from HA by changeing/set new temp to id: 47398 in this case. I suppose tha id is the set temp in F750. 
As mentioned it is poșsible to do so in another app "Tibber".

**Comment by msandvold** [comment]
Any News?

**Comment by elupus** [comment]
The config you posted can't be the exact config right? Can you post the full config section you have?

**Comment by msandvold** [comment]
Here it is:

nibe:
  systems:
    - system: xxxxxxxxxx
      climates: True
      water_heaters: True
      sensors: True
      units:
        - unit: 0
          categories: True
          statuses: True
      sensors:
      - 48132
      - 47041
      - 43437
      - 47398
      - 43001
      - 47275
      - 45001
      switches:
      - hot_water_boost
      - ventilation_boost
      thermostats:
        01:
          name: 'Termostat Nibe'
          current_temperature: sensor.temperature_16
          systems: 1

**Comment by elupus** [comment]
Looks right. And can you give me a screenshot of the thermostat more info card, or the state in decelopertools?

**Comment by msandvold** [comment]
![Screenshot_20211118-234848](https://user-images.githubusercontent.com/79774666/142509327-1d6734bc-bd39-4a06-a24b-79bffc26da59.jpg)

![Screenshot_20211118-234920](https://user-images.githubusercontent.com/79774666/142509345-6f91153a-c5db-4775-b6c1-8732aebc0929.jpg)

**Comment by elupus** [comment]
Ok. Looks correct. I am not sure you will see anything changed on the set temperature parameter of the heat pump. It will just adjust the heat curve a little but. 

That said, you should see the thermostat here: `https://nibeuplink.com/System/[PUT YOUR SYSTEM ID HERE]/SmartHome/Thermostats`

**Comment by msandvold** [comment]
That is the part that I can not figure out.
Smart home mode is Active.
But the thermostat does not appear  in nibeuplink.com....

**Comment by elupus** [comment]
Can you change the id you set "01" to just a "1" without quotes. Maybe it gets confused by the leading zero.

**Comment by msandvold** [comment]
That is the part that I can not figure out.
Smart home mode is Active.
But the thermostat does not appear  in nibeuplink.com....

**Comment by msandvold** [comment]
![Screenshot_20211119-120457](https://user-images.githubusercontent.com/79774666/142612607-a7d31d7d-526f-4c28-aaed-e84ea5ccf927.jpg)

![Screenshot_20211119-120354](https://user-images.githubusercontent.com/79774666/142612624-7c3acf40-55d9-4811-bd84-63ffa909e575.jpg)

**Comment by elupus** [comment]
have you checked your logs? maybe uplink is rejecting data?

**Comment by msandvold** [comment]
HI - You are absolutelig right:

Log:


Logger: homeassistant
Source: custom_components/nibe/climate.py:547
Integration: Nibe Uplink Heat Pumps (documentation)
First occurred: 19:53:20 (3 occurrences)
Last logged: 20:15:20
Error doing job: Task exception was never retrieved

aiohttp.client_exceptions.ClientResponseError: 400, message="{'httpStatusCode': 400, 'errorCode': 23, 'timestamp': '2021-12-17T18:53:14.2556817Z', 'details': ['The client connecting is unknown'], 'data': None}", url=URL('https://api.nibeuplink.com/api/v1/systems/110756/smarthome/thermostats')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nibe/climate.py", line 430, in changed
    await self._async_publish()
  File "/config/custom_components/nibe/climate.py", line 547, in _async_publish
    await self._uplink.post_smarthome_thermostats(self._system_id, data)
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/uplink.py", line 301, in post_smarthome_thermostats
    await self.post(
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/uplink.py", line 92, in post
    return await self.session.request(
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/session.py", line 186, in request
    await raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/nibeuplink/session.py", line 26, in raise_for_status
    raise UplinkResponseException(data.get("errorCode"), data) from e
nibeuplink.exceptions.UplinkResponseException: UNKNOWN_CLIENT: Client connecting is unknown.
{'httpStatusCode': 400, 'errorCode': 23, 'timestamp': '2021-12-17T18:53:14.2556817Z', 'details': ['The client connecting is unknown'], 'data': None}

**Comment by elupus** [comment]
That looks really odd. I think you should remove config entry for nibe, restart, make sure nothing with NIBE is logged on startup, re add the entry.

**Comment by msandvold** [comment]
Hi, Again.
Seems like, if You have a nibe room sensor (temp) innstalled. You Are able du adjust temperature using "S1 Room" (climate.nibe_xxxxxx_s1_room).
Problem solved for now :)
