### ISSUE TITLE
Nibe Uplink setup

### ISSUE THREAD

**Issue by papagooo** [elupus/hass_nibe#108]
Has anybody successfully installed the nibe integration? 
If so, please can you navigate me through the setup process and be more precise than the existing description as this is obviously not adapted to the actual HA version. The screenshots in doc are very different then my actual version on core-2021.10.1

When doc says: "Go to the Integrations page located in Home Assistants Configuration dashboard." My integrations page does not show any configuration link nor does it show a nibe integration.

\custom_components\nibe\ has been created and content exists as shown in doc.

So where can I get the config page to setup the callback url and stuff?

Thanks a lot.

**Comment by elupus** [comment]
Ps. This is much better to take on community forum.

**Comment by traverza** [comment]
I'm also having the same issue. I've downloaded the repository, copied it into the \custom_components\nibe\ but I can't add is as an integration. In the Core log I'm getting only one line:

2021-10-09 11:01:00 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nibe which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

I've successfully installed nibe uplink integration several times in the past following this exact procedure, but I'm having no luck on a fresh HassIO installation today.

**Comment by traverza** [comment]
So I've solved it on my end when I was trying to install it through HACS. The integration (HACS or Nibe) wouldn't show until I've  cleared brower cache (CTRL+F5). The HACS installation guide has this mentioned - https://hacs.xyz/docs/configuration/basic
