### ISSUE TITLE
cannot find any devices nor entities after successful setup of integration

### ISSUE THREAD

**Issue by thomasbachleitner** [elupus/hass_nibe#115]
Hi, 

I searched the other issues but could not find an answer to my question.
I have done the setup as described and I can see the integration in my HA:
![image](https://user-images.githubusercontent.com/44744567/143861011-d461c6d0-fb57-4dd1-abbc-9d50d1eb7a1e.png)

but I cannot find any devices nor entities.

this is the configuration.yaml part:
nibe:
  client_id: 4c797xxxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: yyy0dyVIa0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  redirect_uri: http://localhost:8123/api/nibe/auth
  systems:
    - system: 0

I am a bit of a newcomer, so maybe this has been addressed already. 
if so, then sorry + please point me to the solution.
if you want me to check some logfiles, pls. let me also know the path, where I can find them...

I have restarted the raspberry on which I am running HA several times already + cleared the cache of the browser.

thanks in advance...

**Comment by elupus** [comment]
The systems section you have in your config is wrong. Please remove that.

If you have latest version of the component, it should auto detect all systems. If you want to disable one, you should find them on the configure button.

**Comment by thomasbachleitner** [comment]
thanks for your quick response, 
but still the same - I have removed the 2 lines ("systems:" + "system: 0")
and rebooted the server.

the config file did not change and I still cannot see any devices/entities.
let me know, if/how I can provide more details.

one thing I realized: the secret has the "yyy" prefixed to what I have received from NIBE.

**Comment by thomasbachleitner** [comment]
![image](https://user-images.githubusercontent.com/44744567/143875843-cb13f289-ba54-45df-bfc9-691edf422bef.png)
![image](https://user-images.githubusercontent.com/44744567/143875887-d79465ad-410c-433c-b74e-c223332bb5b3.png)

**Comment by elupus** [comment]
I would start over. Remove integration,  remove config from yaml. Verify that your system is visible from https://nibeuplink.com, (note, this is NOT myuplink).

Add integration from GUI and enter client id and secret when asked for.

**Comment by thomasbachleitner** [comment]
hmm - this is probably the problem - but I cannot connect....

![image](https://user-images.githubusercontent.com/44744567/143885969-d20a8b89-c160-402b-a640-dbc9867a5f56.png)

using the serial number + the string the unit displays. any hint?

the page finds the system with the serial number and I have checked the strings many times.

**Comment by thomasbachleitner** [comment]
oh no...
![image](https://user-images.githubusercontent.com/44744567/143897231-48696a20-092f-4dfb-af57-31137b6d21c1.png)

**Comment by thomasbachleitner** [comment]
this is strange, because I have the myuplink-app on my mobile...
and I see the menu on the machine with the connection string.

**Comment by elupus** [comment]
Myuplink and NIBE uplink are stupidly different systems. They are similar, but a pump can only connect to one of them. 

This integration currently only support NIBE uplink. I would accept clean pull requests to add support for myuplink, but i wont add it without a pump that support it. Sorry.

**Comment by thomasbachleitner** [comment]
Hi - does that mean, if I disconnect from the my-uplink app, I will be able to connect to NIBE-uplink?

**Comment by elupus** [comment]
No. You need another heat pump that connect to nibeuplink instead of myuplink. Not the S series. 

Feel free to complain to NIBE about their silly change.
