### ISSUE TITLE
Set BA-SVM 10-200 to Heat/Cool by default

### ISSUE THREAD

**Issue by tomrennen** [elupus/hass_nibe#118]
Whenever I try to change temperature while my system is set to `heating` state, the temperature doesn't update on the device. However when I set it to `heat_cool` manually, and then update the min_temp it works flawlessly. Problem is, whenever I restart home assistant, the `climate` component reverts back to `heating` by default. I think this might be device specific, so this might have to be hard coded for just BA-SVM 10-200? Or is there something else I can do to workaround this?

**Comment by elupus** [comment]
Yup, this is a bug. Seems it never detects the heating mode. It just assume heat on startup. Yet if it's in just heat, you can't set a value. How silly. Will see when I can fix.

**Comment by elupus** [comment]
Are you doing this from the gui or from automations? When it's on heating, you should be setting just temperature, not low temperature. (Probably should support it as well)

**Comment by elupus** [comment]
Hmm.. i just looked at this again. I can't see how this could occur. It should work just fine when in HEAT mode. You should either be able to set low temp, or standard temp. Might make sense to always be in HEAT_COOL. But it doesn't need to be in that mode.

Which climate entity is it you try to modify?

**Comment by tomrennen** [comment]
Sorry for late replies, github didn't think I'd like to be notified sadly.

Let me clarify a bit:
Whenever I change temp from Home assistant GUI on the default thermostat (S1 Room, physical one in my living room, so not a custom smart thermostat), nothing happens irl and on nibeuplink.com and the value reverts back after a couple of seconds. Whenever I change the mode to Heat/Cool, it works perfectly fine if I change the lower temperature through home assistant GUI.

I've tried creating a smart thermostat, which pointed to the S1 Room temperature as a temperature sensor. This allowed for (the expected) temperature changes through the GUI in heating mode but created an infinite loop as the virtual thermostat was pointing to the unit's temperature which was pointing to the virtual thermostat's temperature, meaning the temperature reading got stuck on 23 degrees.

After looking at the API docs, could it be that `heat` mode modifies the "parallel adjustment" and  `heat_cool` modifier "Target temp while heating" and "Target temp while cooling"? Complete guess, as I have 0 python experience and I couldn't find the answer in the code sadly.

**Comment by elupus** [comment]
when in heat mode. Setting a value should affect same thing as low temp , when in heat_cool mode. I first thought there was a bug, but looked at the code again and couldn't see it.

**Comment by elupus** [comment]
Might have found the issue.. will check later.

**Comment by NickSutton** [comment]
Hi, seeing this also, as per latest comments here: https://community.home-assistant.io/t/nibe-uplink-api-component/18173/654?u=hugosdad

Let me know if I can help in any way!

**Comment by elupus** [comment]
fixed now i think.
