### ISSUE TITLE
Nibe doesn't show up as an integration

### ISSUE THREAD

**Issue by pasberg** [elupus/hass_nibe#124]
Hey,
Thanks for a great integration. However, in my latest setup of HA, I cannot find the integration in the integration list after installing it through HACS and restarting HA (and emptying the browser cache). The log doesn't specifically mention nibe except that one that it is a custom integration.

**Comment by elupus** [comment]
It should show up in the list. Not tested a clean install in a while, but there have been many issues with browser cache.

You could start an incognito browser session and see if you see it there.

**Comment by pasberg** [comment]
Thanks, that did the trick! :)
