### ISSUE TITLE
Hot Water Comfort Mode

### ISSUE THREAD

**Issue by NickSutton** [elupus/hass_nibe#129]
Hi,

Am wanting to automate the hot water mode between 'smart control' (whatever that even is, just does what it wants!) and 'economy' for night times and when out of the house.

I have the entity reporting correctly in HA, but there doesn't appear to be a service to update the entity state and write back to the Uplink. Is it possible?

Thanks

**Comment by elupus** [comment]
The only thing nibe allows you to control is hot water boost. So that i don't think is possible. There is a service for set_parameter that can try to set any parameter, but doubtfull it is allowed.

**Comment by NickSutton** [comment]
Thanks, do you have an example of formatting the data in that service?

**Comment by NickSutton** [comment]
Something like: 

`'47041': 0` looking at the following image but no joy at the moment


![Screenshot 2022-02-21 at 07 31 37](https://user-images.githubusercontent.com/24848258/154908663-e11af859-5078-4f06-a081-e98812a825c5.png)

**Comment by elupus** [comment]
You can use the service in home assistant. set_parameter

**Comment by NickSutton** [comment]
Yes, seen that, but what do I use as the service data?

(It looks as if comfort mode underlying values as 0 - 4)

<img width="493" alt="Screenshot 2022-02-21 at 17 46 56" src="https://user-images.githubusercontent.com/24848258/155005125-65cfc038-c871-49d7-976f-4ba653a433c1.png">

**Comment by NickSutton** [comment]
Have binned this idea in favour of the built in schedules on the Nibe app. Am now just powering off hot water heating during part of the night. Would have been cool to do it via home assistant though, as the scheduling is kind of limited and would like to tie it in to when i’m out of the house etc

**Comment by NickSutton** [comment]
> Have binned this idea in favour of the built in schedules on the Nibe app. Am now just powering off hot water heating during part of the night. Would have been cool to do it via home assistant though, as the scheduling is kind of limited and would like to tie it in to when i’m out of the house etc

Turns out ‘Off’ in the nibe schedule is ‘schedule is off’ rather than ‘hot water is off’ if anyone else is looking, a better way may be to toggle holiday mode, but still unclear off that can be achieved via the API
