### ISSUE TITLE
Installing on Hass.io

### ISSUE THREAD

**Issue by a94marbo** [elupus/hass_nibe#13]
I was trying to add this repository in hass.io, byt adding "https://github.com/elupus/hass_nibe" in the add-on store. But I received a message, that repository.json file is missing for hass.io integration.
Is this something the creator can fix in order to hass.io users to be able to use this nice component as well? If that is the only this that is needed....

**Comment by elupus** [comment]
It's no add-on. It's just a custom config. It should be enough to add it to your config.
