### ISSUE TITLE
Heat pump offset as thermostat

### ISSUE THREAD

**Issue by pacco788** [elupus/hass_nibe#130]
Hey, thanks for this great integration.

I've already realized some automations with it like setting a fan boost if CO2 level on Netatmo station is too high. There is only one thing missing to make it perfect for me: a thermostat to set the temperature at home. My F750 has no indoor thermostat, the temperature in my house is set by the offset factor. Offset 0 is 22°C, offset 1 is 23° C, offset -1 is 21° C. I am only able to control the offset by setting a switch to 0 or 1  in the config.yaml in the with

` nibe:
  systems:
    # System identifier to add extra entities too
    - system: XXXX

      # Optional list of switches (note, for ability to change, you need to use writeaccess and have payed license).
      switches:
        - 47011
`

But I'm unable to make a thermostat in the HomeAssistant UI. I'd like to have an option to set the temperature from 18 to 24 degrees (offset -4 to +2). Any thoughts on that? Is this possible?

Thanks for reply.

**Comment by elupus** [comment]
Create a smart thermostat as per config examples and just link a temp sensor to it.

**Comment by elupus** [comment]
As long as smart sensors are enabled in your pump, the setpoint of the created climate entity will control your pump.
