### ISSUE TITLE
Integration not visible in WebUI

### ISSUE THREAD

**Issue by Vagabond80** [elupus/hass_nibe#133]
Hi,

I recently installed the integration through the HACS repository, but when I tried to configure it through the Integration screen I could not find it, so the API token could not be fetched. After intense googling I found this post: https://community.home-assistant.io/t/nibe-uplink-api-component-non-s-series/18173/15 from 2017. I went to the Integrations page through the IOS app and I was able to fetch the token and all the data is now available in my home assistant. Do you think this issue comes from the integration or is it Home Assistant related? Is it a common issue?

**Comment by elupus** [comment]
Browser sometimes need to be refreshed/cache flushed for custom integrations to show up.

**Comment by elupus** [comment]
Closing since i've not heard anything back
