### ISSUE TITLE
Cooling not reflected in hvac_mode

### ISSUE THREAD

**Issue by tomrennen** [elupus/hass_nibe#137]
My BA-SVM100/6 doesn't reflect cooling in the `hvac_action` attribute of the `s1_room` entity. I've found an earlier issue that states it is supposed to say `cooling` for `hvac_action` when it's actively cooling.

This is what's shown for `s1_room`:
![Screenshot_20220615-175110_Home Assistant~2.png](https://user-images.githubusercontent.com/14904652/173872896-5212569f-fef8-46f8-8fd4-db74ca4f2e20.png)

Meanwhile in Nibe Uplink this is shown:
![Screenshot_20220615-180253_Firefox~2.png](https://user-images.githubusercontent.com/14904652/173879684-5d678b8d-d8b5-4fad-b463-6ad4d881d107.png)

Hopefully this is not an API limitation, just a small oversight. I could also check for `compressor out` < 20 to indicate cooling, but that's not very foolproof.

**Comment by elupus** [comment]
It should support it, but its nothing i've been able to test.
https://github.com/elupus/hass_nibe/blob/7a232d730f9574afa90a49e5498f290b380fed74/climate.py#L162

I wonder if your status is "Cooling (Active)" as indicated by your screenshot.

**Comment by tomrennen** [comment]
It might just be! Is this coming from `https://api.nibeuplink.com/api/v1/systems/{{systemId}}/status/system` ? I will keep an eye on `nibeuplink.com` and do a manual call to check for the json response. Will post back.

**Comment by elupus** [comment]
Yup. Check what that endpoint report, then we can adjust the check.

**Comment by frank8the9tank** [comment]
I have started the cooling today for my heatpump, same problem here, cooling status is not show.

**Comment by frank8the9tank** [comment]
Its something that has worked before, its like its missing in the last couple of updates.

**Comment by elupus** [comment]
Might be that "Cooling (Active)" is a new string from the service. I will add it when i get the time.

**Comment by elupus** [comment]
Should be fixed in https://github.com/elupus/hass_nibe/releases/tag/1.5.1

**Comment by frank8the9tank** [comment]
For me this fixed it.
