### ISSUE TITLE
Error adding entities for domain sensor with platform nibe - following update HA2022.4.7 to HA2022.6.7

### ISSUE THREAD

**Issue by OOO-000-OOO** [elupus/hass_nibe#138]
Hi,

The Nibe Uplink integration sensors stop working/become unavailable whenever I update from the HA 2022.4.7 version to any more recent version.

Only a limited number of sensors remain available while
 others are not responsive.

Any recommendations for corrective actions to take?

_Screenshot sensors not longer available_ 

![2022-07-05_21-31-36](https://user-images.githubusercontent.com/108723739/177404826-cd8c6eac-71be-4bd6-9989-e9bc264e6cd5.png)

_Screenshot error log sensor_

![2022-07-05_21-52-59](https://user-images.githubusercontent.com/108723739/177405658-dca50117-233f-4b14-b5e7-281c9a604242.png)

_Overview Nibe Error log - with duplicates removed_

[Extra Nibe Error logs.pdf](https://github.com/elupus/hass_nibe/files/9049156/Extra.Nibe.Error.logs.pdf)

**Comment by elupus** [comment]
Perhaps start by also updating nibe component?

**Comment by OOO-000-OOO** [comment]
> Perhaps start by also updating nibe component?

Can you specify? I've copied all the files of your 1.5.1 hass_nibe update to the custom_components folder, reloaded the integration and receive these error notification as listed above.

Any additional action to take?

**Comment by OOO-000-OOO** [comment]
Thanks after doing a full re-install everything worked.

**Comment by elupus** [comment]
I suggest you use HACS component to install custom components , so you can keep them up to date.
