### ISSUE TITLE
NIBE Uplink API Major Change

### ISSUE THREAD

**Issue by Ahrgh** [elupus/hass_nibe#14]
Hi
Are you aware of the planned changes on January 31, 2019?

https://mailchi.mp/8decd30b962b/nibe-uplink-planerat-underhll-3528197?e=f356ff9c03

Tks for your great work!

/M

**Comment by mar-schmidt** [comment]
Yeah, I really hope this can will be handled in time...

**Comment by elupus** [comment]
There should be no issue. It's using standard python requests library. It should support later encryptions.
