### ISSUE TITLE
TLS 1.2 now enforced by Azure

### ISSUE THREAD

**Issue by imist** [elupus/hass_nibe#144]
Running latest version of HA and hass_nibe I get this when hass_nibe is starting up (all sensors are unavailable n HA):

`2022-09-01 06:36:11.356 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for nibe
aiohttp.client_exceptions.ClientResponseError: 500, message='', url=URL('https://api.nibeuplink.com/oauth/token')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/nibe/__init__.py", line 207, in async_setup_entry
await session.open()
File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 89, in open
await self.refresh_access_token()
File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 148, in refresh_access_token
await raise_for_status(response)
File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 30, in raise_for_status
raise UplinkException(data) from e
nibeuplink.exceptions.UplinkException: <!DOCTYPE html>
<html>
<head>
<title>JpiKeyVault Exception!:AADSTS1002016: You are using TLS version 1.0, 1.1 and/or 3DES cipher which are deprecated to improve the security posture of Azure AD. Your TenantID is: 9ad3cbc7-2522-4a4a-959a-9b21d005fb68. Please refer to https://go.microsoft.com/fwlink/?linkid=2161187 and conduct needed actions to remediate the issue. For further questions, please contact your administrator.<br>Trace ID: cd6ab26f-9292-44ca-877c-aa1ba23c2400<br>Correlation ID: f29d85eb-7676-4dcf-ad73-a621e995eab5<br>Timestamp: 2022-09-01 04:36:09Z</title>
<meta name="viewport" content="width=device-width" />
`

More info: https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/enable-support-tls-environment?tabs=azure-monitor

Btw, Nibes mobile app seems to have the same issue.

**Comment by elupus** [comment]
Yea it is an issue on nibes servers.

**Comment by imist** [comment]
Ah, ok. At first I thought it was the clients (hass_nibe & Nibe mobile app) that needed to be updated to support TLS 1.2.

**Comment by priiduonu** [comment]
Seems to be solved?
