### ISSUE TITLE
Feature req: Power and energy entities without external sensor.

### ISSUE THREAD

**Issue by AndersHoglund** [elupus/hass_nibe#146]
Would it be possible to add a couple of artificial entities for total Power and Energy by computations based on input voltage and current? 
My F730 reports current per phase but I guess voltage needs to be assumed 230V or 400V, or taken from some other source if available. Strange that Nibe only reports additional power used, but not total. And no energy used nor produced. An energy system that does not report any energy values .....

**Comment by elupus** [comment]
It would not be true anyway since you wont be getting the reactive power correct.

**Comment by elupus** [comment]
I dont think i want to add calculated entities like that.

**Comment by Marrrs** [comment]
@AndersHoglund - I actually use the sensor template in issue #127 to read the consumed kw/h successfully. I entered V1-V3 as 238 volts and power factor 88.8. I read this value every minute and multiply it with Tibber's price for the hour/60. This is added to a input number helper which resets monthly. Weirdly enough it is fairly accurate when compared to Tibber's monthly cost. 

This was just a parenthesis, I totally respect the desicion to leave this out of the integration.

**Comment by elupus** [comment]
The current per phase, is that not the whole house load monitoring sensors? They are not reporting pump only.

**Comment by AndersHoglund** [comment]
@Marrrs The issue is not total consumed energy by the household, only the Nibe F730. I get household total consuption from power meter and solar inverter.

**Comment by AndersHoglund** [comment]
@elupus I have no load monitoring sensors, yet I have varying current per phase values. I of course assumed that was the pump consumption. 

Also, power and energy never can be measured directly;  They have to be computed from voltage, current, phase angle and time. Big Q is who should do that? As Nibe does not, weird enough, someone else could try and do it, If base data are available....

**Comment by elupus** [comment]
Yes, the current per phase are sensors added at your house firat entry point, it measures everything in your house. Its used to adapt the pump load based on other consumers in your house.

**Comment by elupus** [comment]
If you have an actual meter (with numbers on i, or pulse putput) in that sub central that sounds like a valid meter. It doesnt need to be hooked up to the pump though.

The houshould current metering is just 3 black clamps that is placed on house incoming supply to do load adjustments for when you have other high loads.

**Comment by aadnehovda** [comment]
I added an integral sensor on the "electrical addition power" sensor, which I then could add to the energy dashboard. I don't know how accurate that is, and it only reports on the heating element and not the fan, compressor and other power used by the heat pump. 

```yaml
sensor:
  - platform: integration
    source: sensor.nibe_132271_43084
    method: left
    name: sensor_nibe_132271_43084_integral
    unique_id: sensor_nibe_132271_43084_integral
```
![image](https://user-images.githubusercontent.com/1244723/195096887-d04535be-e604-48ea-8fd1-f329afcdd1f3.png)
