### ISSUE TITLE
Temperatur adjustment bug?

### ISSUE THREAD

**Issue by msandvold** [elupus/hass_nibe#147]
Hi.
Comparing two thermostats in my system, it seem like somethings are chenged, probably avfter HA is updated to the latest version.
Using "Thermostat Card" it is possible to adjust tempt for my Nibe F750 "climate.nibe_xxxxxx_s1_room", but no info are showing using another layout. Only "Target temperature". In the other Thermostat it is able to adjust.

See attached pics.
![Thermostat_S1_Room](https://user-images.githubusercontent.com/79774666/189311575-b2ce8e80-9bfe-41fe-b743-1ee3f882eec1.JPG)
![Thermostat_S1_Room_card](https://user-images.githubusercontent.com/79774666/189311583-1bf1d3e9-0824-4dd9-9e6f-30089102b2b7.JPG)
![Thermostat_tado_radiator_tv_krok](https://user-images.githubusercontent.com/79774666/189311585-bc7de92b-39c9-4fc2-8a41-781eabef74c9.JPG)

**Comment by elupus** [comment]
Hmm. Looks like a home assistant bug. Will investigate.

**Comment by elupus** [comment]
https://github.com/home-assistant/frontend/pull/13638 this is what broke it i think.

**Comment by msandvold** [comment]
I think You are right 👍

**Comment by elupus** [comment]
Should have been resolved in latest patch release.

**Comment by msandvold** [comment]
Hi.
This case does not seem to be fixed in 2022.9.3.
Same result AS mentioned above.
Hopefully it will be OK in the next release/update.

**Comment by elupus** [comment]
Ok. The change is reverted upstream. I thought this change made the cut for the point release. Well see on next.

**Comment by msandvold** [comment]
Fixed :)
