### ISSUE TITLE
Unable to load sensors on hassbian

### ISSUE THREAD

**Issue by lorddaku** [elupus/hass_nibe#15]
<img width="371" alt="skarmavbild 2019-01-05 kl 11 19 41" src="https://user-images.githubusercontent.com/44786872/50727293-33a7cb80-1119-11e9-99d3-0e1a7b03d2c4.png">
<img width="636" alt="skarmavbild 2019-01-05 kl 18 44 08" src="https://user-images.githubusercontent.com/44786872/50727383-7b7b2280-111a-11e9-859c-2f01f3adf6ab.png">

<img width="572" alt="skarmavbild 2019-01-05 kl 18 41 45" src="https://user-images.githubusercontent.com/44786872/50727319-9600cc00-1119-11e9-99de-f651e5a88b91.png">

I have installed on hassbian 0.84.6 and followed the instructions. I have gained success in auth against api.nibeuplink.com. After that I get errors in the log that sensors cannot be loaded I also get an error message in the HA front end. see attached dumps.

**Comment by elupus** [comment]
Looks like you may have placed the files for the sensors in wrong folders. The folder structure must be identical to the repo.

**Comment by lorddaku** [comment]
Ok.
Should the folder in custom_components be called "nibe" or "hass_nibe"? When I clone from the repository it gets the name "hass_nibe" I have at least entered the files in custom_components / nibe but then I get the following errors in the log:
2019-01-05 21:49:56 ERROR (MainThread) [homeassistant.loader] Unable to find component nibe
2019-01-05 21:49:56 ERROR (MainThread) [homeassistant.setup] Setup failed for nibe: Component not found.

**Comment by lorddaku** [comment]
ok, now i understand. repo direct under cc. now it's working. :)
