### ISSUE TITLE
AUX temperatur sensors

### ISSUE THREAD

**Issue by skroes** [elupus/hass_nibe#151]
in HA i noticed these naming (english/dutch)
external flow temp. BT25 // externe aanvoertemp // BT25

in HA these are in the integration available in section: soft in/outputs

these are visible in HA;
![flameshots_4](https://user-images.githubusercontent.com/828277/191281809-83412506-e387-4509-a468-975e9b5b5cb7.png)

but BT25 is visible, as integer, in the attribute raw_value

![flameshots_5](https://user-images.githubusercontent.com/828277/191282318-88268506-ebf4-483d-b2a7-1e500dd6ecab.png)

**Comment by elupus** [comment]
The raw value 27 is not the temperature i think. It's just the configuration option for external flow temp. However seems AUX6 is missing. What parameter id does AUX6 have?

Ps. Your actual temperature on BT25 should be on 40071
