### ISSUE TITLE
"Degree" (Celsius) looks wird for 40121

### ISSUE THREAD

**Issue by oz9els** [elupus/hass_nibe#156]
This is the current values:

state_class: measurement
designation: BT63
parameter_id: 40121
friendly_name: addition temperature
display_value: 24.8ºC
raw_value: 248
display_unit: ºC
unit_of_measurement: ºC

Not sure it shows the difference, but the "Degree" symbol is different from all other "degree" in the integration
Below is correct/like all the other instances of "Degree"
display_unit: °C
unit_of_measurement: °C

**Comment by hvt** [comment]
Couldn't really find this directly in this project's source, but I bet it has something to do with BT63 usually being on one of the auxiliary inputs (e.g. `AUX1`).

I worked around this by adding a custom override in `configuration.yaml` like this:

```yaml
homeassistant:
  customize:
    sensor.nibe_172453_40121:
      unit_of_measurement: '°C'
```

After a restart, and once a new value for `AUX1` came in, you can use BT63 as a temperature like you expected.
