### ISSUE TITLE
List of parameters using Postman

### ISSUE THREAD

**Issue by B1rdEater** [elupus/hass_nibe#158]
Hi!

I've succesfully managed to install the integration; but now trying to find out which data my heatpump shows through its Nibe uplink API.

If I understand correctly, one could do a API GET request (api/v1/systems/{systemId}/serviceinfo/categories?parameters=true). How do I do this with Postman? Can anyone help me out?

Questions:

- what is my SystemID?
- how do I get the correct Authentication?

**Comment by elupus** [comment]
If you add it in home assistant you get all the API reports. You can also see the system id there.

With the commandline client in nibeuplink python lib you can list the systems and get the system id there.

Not really an issue with the integration so im going to close.

**Comment by B1rdEater** [comment]
Thanks for the quick reply!

The integration is made in a way that ALL entities that the API reports are translated to sensors?

**Comment by elupus** [comment]
It is mostly all sadly. There are one or two extras ive seen, but its far from all the pump supports. The extras ive found (forgotten which) where not interesting.

To get all parameters you need local access.

**Comment by B1rdEater** [comment]
Thanks! Didn't know that :). I read all these things about more info being available (but that should have been local, and not through API). Thanks for clearing that up.
