### ISSUE TITLE
Template Sensor - Unavailable

### ISSUE THREAD

**Issue by MichaelRV82** [elupus/hass_nibe#159]
Hi Guys,

after doing some reading in the issue threads here, I tried to implement a solution with a sensor template:

#103 

![image](https://user-images.githubusercontent.com/92013548/206205853-24c03713-6072-4ec0-8f20-d2942465ee81.png)

my two template sensors are always unavailable although the origin sensors are up and running and also filled with value.

Is anything wrong with my syntax or why do this template sensors stay "unavailable"

Thanks,
Michael

**Comment by elupus** [comment]
Not an issue with this addon. Can not support on template syntax.
