### ISSUE TITLE
The ability to set dgree minutes

### ISSUE THREAD

**Issue by Tboyten** [elupus/hass_nibe#160]
Is there a way to add the ability to change settings in the menu for degree minutes. Meny  4.9.3

**Comment by elupus** [comment]
Not allowed by api as far as i know.

**Comment by Tboyten** [comment]
I suspected that. It would have been great if it were possible. A good way to save a some electricity.

**Comment by elupus** [comment]
You would have to switch to local access to the pump with something like: https://github.com/elupus/esphome-nibe

But only an option if you are the tinkering type :)

**Comment by Tboyten** [comment]
It is something similar to https://github.com/anerdins/nibepi. I have a Raspberry Pi lying around, but I haven't dared to try the physical things yet on the machine. Maybe it's time to figure it out.

**Comment by elupus** [comment]
Similar yes. But just for interfacing to some other system. A nibegw unit like linked can be used for either home assistant or nibepi.

**Comment by elupus** [comment]
Ps. You can use a raspberry with linux and a linux nibegw. But if you dont intend to run nibepi directly i suggest something simpler.

**Comment by Tboyten** [comment]
Ok, interesting topic. I will definitely continue my investigation and get something working. Maybe even mail or call Nibe and ask them to enable it. We both are from Sweden so maybe it will help. :)

Thank you very much for your quick replies and recommendations. It's a great integration that I use daily. Thanks for that too.

Merry christmas to you!

**Comment by elupus** [comment]
Merry christmas!
