### ISSUE TITLE
Different history view of an entity in 1.5.6

### ISSUE THREAD

**Issue by henriklundqvist** [elupus/hass_nibe#163]
Hi,

I have a Nibe F750 that have an entity called sensor.nibe_77017_40050 (value, air velocity sensor) that in version 1.5.5 showed the history in graphs but in the 1.5.6 version it started to show history in another view. See attached pictures.

Is this something that can be resolved?

Many thanks
/Henrik

![1 5 5](https://user-images.githubusercontent.com/97613649/221809132-987f407c-14c2-4dd5-a966-3d79e08c5723.png)
![1 5 6](https://user-images.githubusercontent.com/97613649/221809155-1f92f4e8-b7c7-459a-8656-bfa5a0585475.png)

**Comment by imist** [comment]
What do your attributes look like?Here are mine still running v1.5.5:Michael28 feb. 2023 kl. 10:24 skrev henriklundqvist ***@***.***>:﻿
Hi,
I have a Nibe F750 that have an entity called sensor.nibe_77017_40050 (value, air velocity sensor) that in version 1.5.5 showed the hostory in graphs but in the 1.5.6 version it started to show history in another view. See attahced pictures.
Is this something that can be resolved?
Many thanks
/Henrik

**Comment by elupus** [comment]
It's likely lacking a number unit. Previously some had a single space as unit. This however is rejected by newer home assistant so i had to remove that.

**Comment by imist** [comment]
Is it possible to set unit_of_measurement: m3/h instead for 40050 and 43124?

**Comment by henriklundqvist** [comment]
> What do your attributes look like?Here are mine still running v1.5.5:Michael28 feb. 2023 kl. 10:24 skrev henriklundqvist ***@***.***>:﻿ Hi, I have a Nibe F750 that have an entity called sensor.nibe_77017_40050 (value, air velocity sensor) that in version 1.5.5 showed the hostory in graphs but in the 
![attributes 1 5 5](https://user-images.githubusercontent.com/97613649/222363952-bb41384c-9cb5-473f-9ff7-09aa18eb670e.png)
1.5.6 version it started to show history in another view. See attahced pictures. Is this something that can be resolved? Many thanks /Henrik —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

The attributes look the same for 1.5.5 and 1.5.6, see pictures below:
![attributes 1 5 6](https://user-images.githubusercontent.com/97613649/222363980-503e429f-5282-4007-a1c0-7e5244db626d.png)
![attributes 1 5 5](https://user-images.githubusercontent.com/97613649/222364014-a5a2f972-fc45-4d0a-a2e5-80ab07378d24.png)
