### ISSUE TITLE
Not being able to add integration

### ISSUE THREAD

**Issue by JensKarl** [elupus/hass_nibe#166]
Added the repo through HACS.
Created an account at the api.
After adding the line: 
nibe: 
in the configuration.yaml
I can't add the integration from the integration page. 

Is the readme outdated from the current HAOS?

**Comment by elupus** [comment]
No, but you may need to flush browser cache after adding the repo with hacs.

**Comment by Jarkkolainen** [comment]
> Added the repo through HACS. Created an account at the api. After adding the line: nibe: in the configuration.yaml I can't add the integration from the integration page.
> 
> Is the readme outdated from the current HAOS?

Same for me. Caches flushed but issue persists.

**Comment by JensKarl** [comment]
> No, but you may need to flush browser cache after adding the repo with hacs.

Yes, got it to work. Thank you.

**Comment by Lerxxst** [comment]
I'm having the same issue. Copied repo into custom config - added through HACS - account created in NibeAPI. Page logs in successfully & returns to HA but no evidence of Nibe Uplink within HA.
Am I missing something obvious?

**Comment by elupus** [comment]
@Lerxxst your issue sounds different. If you still have issues after adding the integration. Please open a new issue with debug logs.
