### ISSUE TITLE
F1255-12E, can't gather power consumption

### ISSUE THREAD

**Issue by WhippingBoy01** [elupus/hass_nibe#167]
Model F1255-12E
software version 9443R5

I can't seem to get information regarding power consumption out using the integration

![Screenshot 2023-03-28 12 55 09](https://user-images.githubusercontent.com/56207689/228214564-0cca4b79-f7c0-4ce4-8770-8d89b1dfbb2a.png)

**Comment by elupus** [comment]
Your pump does not provide this information without other external accessories.
