### ISSUE TITLE
Very slow startup times in HA 2023.4.1

### ISSUE THREAD

**Issue by elden1337** [elupus/hass_nibe#168]
Hi, 
Don't know if i'm the only one experiencing this matter, but since updating to latest HA-version (not beta) the integration has become extremely slow.  Startup times vary, but between 3-10 minutes seems to be the pattern i'm getting.

Logs aren't telling me much, and I don't see anything on top of mind in the code that I could easily PR to make it faster.

**Comment by elupus** [comment]
A couple of minutes is expected due to throttling. But are you saying lts slower than before?

**Comment by elden1337** [comment]
yes, that's the impression, but just now i got a virtual rubber duck from you since it only took the regular ~150s ;). 
my own peaqev is also significantly slower after the ha-upgrade, but not the rest of my integrations. 
will check. i you don't notice it and noone else please just close this issue, i merely wanted to raise the concern but haven't found any proof in your code as to what could have caused it.

**Comment by elden1337** [comment]
Think it was a temp anomaly, perhaps db-reindexing or something. Back to normal startup times now most of the time. Closing
