### ISSUE TITLE
power consumption parameters on VVM320

### ISSUE THREAD

**Issue by Vagabond80** [elupus/hass_nibe#169]
This is not really an issue of this integration but more an ask for help from other NIBE Users. My VVM320 returns 4 power consumption parameters:

![image](https://user-images.githubusercontent.com/102099720/231398316-bfba5a03-edc2-4388-b8af-80e4dcf45606.png)

Parameter IDs are:

44308 - heating, compr. only.
44300 - heating, int. add. incl.
44306 - hotwater, compr. only.
44298 - hw, incl. int. add

I understand that 44308 and 44300 are for heating and 44306 and 44298 for hot water. But what are those additions?

When I add these parameters to my Energy Dashboard they also do not add up correctly to my actual consumption for that day, they are way too high.:

They show a combined 14 kWh for the day:

![image](https://user-images.githubusercontent.com/102099720/231399522-6aa8de4f-fe5e-4015-983c-6d35d265e742.png)

But my overall consumption was less than 9kWh at that point of time.

![image](https://user-images.githubusercontent.com/102099720/231399682-5b2875e0-9054-4c46-9b68-186fc69e7ece.png)

I am certain I am not understanding something and I hope someone can shed some light on this. I'd really appreciate that.

**Comment by elupus** [comment]
These types of questions are better on forum. No user will read here.

Addition is extra heating with 100% electricity. Ie your pump cant keep up with demand.
