### ISSUE TITLE
Failure to get token

### ISSUE THREAD

**Issue by prlwytzkofsky** [elupus/hass_nibe#171]
Hy, I'm trying to add the heat pump to HA.
I get to the part where I can add the integration, but when authorizing at nibe I get a failure.

1. Configure Uplink parameters, fill out Call back url, done
2. Fill out identifier (is this identifier for nibe or for HA?)
3. Fill out password (for nibe or HA?)

I then get the login page for Nibe, I fill out the correct password and email but get the error "Failure looking up secret for client or token."

What am I doing wrong?

Thanks in advance

**Comment by elupus** [comment]
Have you registered on api.nibeuplink.com, thats where you get identifers and passwords. Please read readme again.

**Comment by prlwytzkofsky** [comment]
Thank you, found it. 
I did not finish the subscription correctly.
