### ISSUE TITLE
Supporting S735

### ISSUE THREAD

**Issue by amattsso** [elupus/hass_nibe#173]
Hi,

I recently got a new Nibe S735 installed and like to add it to my HA installation.
Can't see that it is supported yet and would very much like it to be.
Added it as a S325 heatpump in the meenwhile just to se that the modbus is fuctional, and it is.
Hopefully it will be fully supported in an upcomming release.

**Comment by elupus** [comment]
This project is for nibe uplink based pumps. To get support for s series pumps, please export the complete parameter list from your pump and attach that to a new issue at: https://github.com/yozik04/nibe
