### ISSUE TITLE
async_setup Error since Home Assistant 2023.5.2

### ISSUE THREAD

**Issue by Minius90** [elupus/hass_nibe#174]
After updating Home Assistant to version 2023.5.2 the integration stopped working. I get the following error. Is there a way to solve this problem?

> Logger: homeassistant.config_entries
Source: loader.py:1045

Error setting up entry for nibe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nibe/__init__.py", line 235, in async_setup_entry
    await async_setup_systems(hass, data, entry)
  File "/config/custom_components/nibe/__init__.py", line 184, in async_setup_systems
    await asyncio.gather(*tasks)
  File "/config/custom_components/nibe/__init__.py", line 298, in load
    device_registry = await self.hass.helpers.device_registry.async_get_registry()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1045, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'

**Comment by Minius90** [comment]
It seems that some other custom integrations also encounter this error. Another user said, this might be the problem:

```
The async_setup_platforms function had been marked deprecated a while back, initially set to fail as obsolete in 2023.3. Now it actually fails in 2023.5, as previously announced.
Since all the messages in this thread are about custom integrations (likely from HACS) the developer of those custom integrations will need to update their integration to use to use await async_forward_entry_setups instead of async_setup_platforms.
```

**Comment by elupus** [comment]
Did you guys think about updating nibe component? The first issue was fixed over a year ago. The second several month's ago.
