### ISSUE TITLE
Integration won't work

### ISSUE THREAD

**Issue by MNibon** [elupus/hass_nibe#176]
I get an error that says that: Det gick inte att ställa in
[Kontrollera loggarna]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nibe/__init__.py", line 235, in async_setup_entry
    await async_setup_systems(hass, data, entry)
  File "/config/custom_components/nibe/__init__.py", line 184, in async_setup_systems
    await asyncio.gather(*tasks)
  File "/config/custom_components/nibe/__init__.py", line 298, in load
    device_registry = await self.hass.helpers.device_registry.async_get_registry()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1045, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'

Is there anything I can do to fix this?
//Mats

**Comment by elupus** [comment]
Update the integration. Fixed a while back.

**Comment by MNibon** [comment]
Hi,I've tried to update the integration, eventuellt re-intalled it, but the problem is still there.Med vänlig hälsning, Mats
-------- Originalmeddelande --------Från: Joakim Plate ***@***.***> Datum: 2023-05-11  12:15  (GMT+01:00) Till: elupus/hass_nibe ***@***.***> Kopia: MNibon ***@***.***>, Author ***@***.***> Ämne: Re: [elupus/hass_nibe] Integration won't work (Issue #176) 
Update the integration. Fixed a while back.

**Comment by elupus** [comment]
Then please try again. The call to async_get_registry does not exist at all in https://github.com/elupus/hass_nibe/blob/master/__init__.py

**Comment by MNibon** [comment]
Now it works!
I reinstalled it  through Repository: https://github.com/elupus/hass_nibe<https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Felupus%2Fhass_nibe%3Ffbclid%3DIwAR02_HVVKksjXNjGBw8QqgpkCsVBMNfb9upWhh0Betp3yCaNNxGD_dCdg28&h=AT3-Qc1gx2rkBxGgwM-TYnw2pLz6D49mozmiEhnL92NBi25VyWED2JUkqLqzkHwqe3StkdJZdq2hRRYDt8kYoEFZP58l23mY2BMX3rH5Vj7PrOERJUi159aX5algRytacA&__tn__=R%5d-R&c%5b0%5d=AT3UWA6jErjNMDqb7en4FWMqOzWm1XMefmiOxoZmQk9SZazEJxwBPfPCHGuvAVZnn_sZElXU2PEj6dm9KeX92YVeRjoUvb05P81-q0zHAjEp3h0S-4Fm07hDs4_3QnjOwzFy2w-l4URoVRA4q0Zh8AIvIVdbg4OT>
Category: Integration
And then it all started to work!

Thanks
//Mats


Från: Joakim Plate ***@***.***>
Skickat: den 12 maj 2023 19:01
Till: elupus/hass_nibe ***@***.***>
Kopia: MNibon ***@***.***>; Author ***@***.***>
Ämne: Re: [elupus/hass_nibe] Integration won't work (Issue #176)


Then please try again. The call to async_get_registry does not exist at all in https://github.com/elupus/hass_nibe/blob/master/__init__.py
