### ISSUE TITLE
Too many requests 

### ISSUE THREAD

**Issue by ouranos6** [elupus/hass_nibe#177]
Hi!

i have an issue with the addon. Sometimes it works and most of the time not. 

`This error originated from a custom integration.

Logger: custom_components.nibe
Source: custom_components/nibe/__init__.py:179 
Integration: Nibe Uplink Heat Pumps (documentation) 
First occurred: May 8, 2023 at 4:24:57 PM (217 occurrences) 
Last logged: 6:47:44 PM

Unexpected error fetching Nibe Uplink data: RATE_LIMIT: Rate limit. Too many requests. {'httpStatusCode': 400, 'errorCode': 28, 'timestamp': '2023-05-13T16:46:47.41097Z', 'details': ['You have exceeded the API request rate limit and have been blocked temporarily.'], 'data': None}
Unexpected error fetching Nibe Uplink data: RATE_LIMIT: Rate limit. Too many requests. {'httpStatusCode': 400, 'errorCode': 28, 'timestamp': '2023-05-13T16:47:14.317435Z', 'details': ['You have exceeded the API request rate limit and have been blocked temporarily.'], 'data': None}
Unexpected error fetching Nibe Uplink data: RATE_LIMIT: Rate limit. Too many requests. {'httpStatusCode': 400, 'errorCode': 28, 'timestamp': '2023-05-13T16:47:17.3330847Z', 'details': ['You have exceeded the API request rate limit and have been blocked temporarily.'], 'data': None}
Unexpected error fetching Nibe Uplink data: RATE_LIMIT: Rate limit. Too many requests. {'httpStatusCode': 400, 'errorCode': 28, 'timestamp': '2023-05-13T16:47:17.4112119Z', 'details': ['You have exceeded the API request rate limit and have been blocked temporarily.'], 'data': None}
Unexpected error fetching Nibe Uplink data: RATE_LIMIT: Rate limit. Too many requests. {'httpStatusCode': 400, 'errorCode': 28, 'timestamp': '2023-05-13T16:47:44.2883874Z', 'details': ['You have exceeded the API request rate limit and have been blocked temporarily.'], 'data': None}
aiohttp.client_exceptions.ClientResponseError: 429, message="{'httpStatusCode': 400, 'errorCode': 28, 'timestamp': '2023-05-08T14:24:57.3316541Z', 'details': ['You have exceeded the API request rate limit and have been blocked temporarily.'], 'data': None}", url=URL('https://api.nibeuplink.com/api/v1/systems')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/nibe/__init__.py", line 179, in _async_update_data
    systems_raw = await self.uplink.get_systems()
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/uplink.py", line 194, in get_systems
    data = await self.get("systems")
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/uplink.py", line 82, in get
    return await self.session.request(
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 186, in request
    await raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 26, in raise_for_status
    raise UplinkResponseException(data.get("errorCode"), data) from e
nibeuplink.exceptions.UplinkResponseException: RATE_LIMIT: Rate limit. Too many requests.
{'httpStatusCode': 400, 'errorCode': 28, 'timestamp': '2023-05-08T14:24:57.3316541Z', 'details': ['You have exceeded the API request rate limit and have been blocked temporarily.'], 'data': None}
`

do you mind to have look into the logs?

thaks in advance

**Comment by elupus** [comment]
Strange. We should not be that close to the limit. You have not modified the update rate?

**Comment by ouranos6** [comment]
Hi,

I didn’t touch anything. I’ve followed the instructions 1,5 years ago and then nothing
________________________________
De : Joakim Plate ***@***.***>
Envoyé : Saturday, May 13, 2023 9:14:17 PM
À : elupus/hass_nibe ***@***.***>
Cc : ouranos6 ***@***.***>; Author ***@***.***>
Objet : Re: [elupus/hass_nibe] Too many requests (Issue #177)


Strange. We should not be that close to the limit. You have not modified the update rate?

**Comment by elupus** [comment]
"then nothing"? Is it that old version of the component, you should start by updating it.

**Comment by ouranos6** [comment]
Yes i’ve done that two days ago restarted my hassio and even the SMO40 but nothing
________________________________
De : Joakim Plate ***@***.***>
Envoyé : Saturday, May 13, 2023 9:28:04 PM
À : elupus/hass_nibe ***@***.***>
Cc : ouranos6 ***@***.***>; Author ***@***.***>
Objet : Re: [elupus/hass_nibe] Too many requests (Issue #177)


"then nothing"? Is it that old version of the component, you should start by updating it.

**Comment by elupus** [comment]
You have only one configuration instance set up? And you are not using the same connection parameters from some other tool reading data from nibe?

**Comment by ouranos6** [comment]
Nop only the addon.

I’ve bought an LilyGo T-CAN485 sometimes ago to use it with another addon but I had no time and no wiring schema to make the connections so I let it down brand new
________________________________
De : Joakim Plate ***@***.***>
Envoyé : Saturday, May 13, 2023 9:32:52 PM
À : elupus/hass_nibe ***@***.***>
Cc : ouranos6 ***@***.***>; Author ***@***.***>
Objet : Re: [elupus/hass_nibe] Too many requests (Issue #177)


You have only one configuration instance set up? And you are not using the same connection parameters from some other tool reading data from nibe?

**Comment by ouranos6** [comment]
Let me try deleting everything and starting from scratch with the hacs installer.

Is it some files do I need to remove from ./Storage or elsewhere?
________________________________
De : Ivan Morgade ***@***.***>
Envoyé : Saturday, May 13, 2023 9:37:23 PM
À : elupus/hass_nibe ***@***.***>; elupus/hass_nibe ***@***.***>
Cc : Author ***@***.***>
Objet : Re: [elupus/hass_nibe] Too many requests (Issue #177)

Nop only the addon.

I’ve bought an LilyGo T-CAN485 sometimes ago to use it with another addon but I had no time and no wiring schema to make the connections so I let it down brand new
________________________________
De : Joakim Plate ***@***.***>
Envoyé : Saturday, May 13, 2023 9:32:52 PM
À : elupus/hass_nibe ***@***.***>
Cc : ouranos6 ***@***.***>; Author ***@***.***>
Objet : Re: [elupus/hass_nibe] Too many requests (Issue #177)


You have only one configuration instance set up? And you are not using the same connection parameters from some other tool reading data from nibe?

**Comment by ouranos6** [comment]
Ok so after removing everything and recreate the credentials on the api page AND authorize it, now it’s working.!!

But I want to try the lilygo with ESPHOME to be offline and more reliable.

If i can do it maybe i want to make a small tuto for the others.
________________________________
De : Joakim Plate ***@***.***>
Envoyé : Saturday, May 13, 2023 9:32:52 PM
À : elupus/hass_nibe ***@***.***>
Cc : ouranos6 ***@***.***>; Author ***@***.***>
Objet : Re: [elupus/hass_nibe] Too many requests (Issue #177)


You have only one configuration instance set up? And you are not using the same connection parameters from some other tool reading data from nibe?

**Comment by elupus** [comment]
Did you see: https://github.com/elupus/esphome-nibe/blob/master/examples/lilygo-t-can485.png
