### ISSUE TITLE
Change comfort mode (water)

### ISSUE THREAD

**Issue by saajs** [elupus/hass_nibe#179]
Hi,

Not sure to ask my question here, but I go for it. 

I was wondering if it's possible to change the water comfort mode via the integration. 

![image](https://github.com/elupus/hass_nibe/assets/23075517/09b10d95-8327-4ecd-84ce-34e96ce22ea4)

Modifying the temporary lux isn't a problem (but is alway very 'drastic'). 

Thanks already for the great integration!

**Comment by elupus** [comment]
It does not seem to be allowed by the API. At least not without a premium subscription. I think people with subscription has tried, but not succeeded.

**Comment by enoch85** [comment]
@saajs Maybe not the answer to your question, but have a look at this: https://github.com/elden1337/hass-peaqhvac It's smart about the water setting.

You need a premium subscription for it t work, and it's enough with the "Change settings" subscription.
