### ISSUE TITLE
Device is disabled by Configuration entry.

### ISSUE THREAD

**Issue by GlimSo** [elupus/hass_nibe#180]
I had a working instance of this Nibe integration but after updating to the latest OS i've experienced issues saying "device is disabled by Configuration entry." 

*I've tried to: *

- Remove and reinstall the integration / restart the system (doing it manually and not through HACS)

- Adding nibe configuration line in config file 

- Authenticaiton works and says successfull + finding the enteties. However, after the enteties are added they automatically gets inactivated with no possible way to activate them 

Any known issues?

**Comment by elupus** [comment]
Check if you have managed to disable one of the devices for the pump.

**Comment by RonaldHelder** [comment]
Hi,

same here. My integration worked til version 9. I upgraded to HA OS V10.5, now the integration is not working anymore. I reinstalled the NIBE Uplink code, reinstalled it in HomeAssistant, can do the authentification at NIBE, but HomeAssistant says Setup failed ("needs attention", "no device nor entities").  In your ReadMe, the last step is somewhat unclear to me (I don't understand...), do I need to do something here ? I didn't in a previous version
When I check the Logfile, it has an entry for NIBE, where it looks like some attributes are missing:

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 4 januari 2024 om 20:54:22 (7 occurrences)
Last logged: 11:27:25

Error setting up entry for nibe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nibe/__init__.py", line 226, in async_setup_entry
    await _async_refresh()
  File "/config/custom_components/nibe/__init__.py", line 224, in _async_refresh
    await _async_add_system(system_raw, _get_system_config(hass, system_id))
  File "/config/custom_components/nibe/__init__.py", line 203, in _async_add_system
    await system.load()
  File "/config/custom_components/nibe/__init__.py", line 312, in load
    device_registry = await self.hass.helpers.device_registry.async_get_registry()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in __getattr__
    value = getattr(self._module, attr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'

**Comment by elupus** [comment]
Upgrade the nibe hass custom component. You are still using a really old version.

**Comment by elupus** [comment]
Please start using HACS to keep it up to date. https://hacs.xyz/

**Comment by RonaldHelder** [comment]
Thank you. I thought I already did that. But now I removed al files from the Raspberry first, reinstalled them, restartet and now it is working again.
