### ISSUE TITLE
Failure looking up secret for client or token.

### ISSUE THREAD

**Issue by Obelixje** [elupus/hass_nibe#182]
I am trying to reinstall the integration.
This, because I want to enable write rights. (I have Nibe subscription now)

After I typed my logon email and name I get errormessage:
Failure looking up secret for client or token. On the Nibe link page.

What can we wrong please?

**Comment by elupus** [comment]
Wrong client id or secret i guess. Verify that the values for those match. (Ps. Secret in config is not your password)

**Comment by Obelixje** [comment]
Did completely forget how I did the setup last time.
you are right, I used the wrong secret id and pass.
