### ISSUE TITLE
All entities unavailable after Home Assistant CORE update

### ISSUE THREAD

**Issue by aigari** [elupus/hass_nibe#183]
![image](https://github.com/elupus/hass_nibe/assets/102829930/909c8626-ee0d-46ad-9b62-94f348d43b77)

**Comment by elupus** [comment]
Start with upgrading the components

**Comment by aigari** [comment]
OK, How should I do it?

**Comment by elupus** [comment]
Same way installed it the first time. I recommend the HACS method.

**Comment by aigari** [comment]
I did my very best, but nothing changed...
I noticed that after restarting it works for a second and then immediately becomes unavailable again.

![image](https://github.com/elupus/hass_nibe/assets/102829930/2c4a8015-c8a3-4b33-ba6a-073bb7bbe2b3)

**Comment by elupus** [comment]
Please check logs and see if you have some errors.

**Comment by aigari** [comment]
Yes, there are some errors:



Logger: homeassistant.components.nibe_heatpump
Source: components/nibe_heatpump/__init__.py:287
Integration: Nibe Heat Pump (documentation, issues)
First occurred: 8:05:14 PM (87 occurrences)
Last logged: 9:31:15 PM

Unexpected error fetching Nibe Heat Pump data: Failed to decode start-temperature-hw-low-temperature-40061 coil from raw: 1400, exception: Raw value 20 is out of range for coil start-temperature-hw-low-temperature-40061
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/encoders.py", line 72, in decode
    return CoilData.from_raw_value(coil, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe/coil.py", line 157, in from_raw_value
    assert coil.is_raw_value_valid(
AssertionError: Raw value 20 is out of range for coil start-temperature-hw-low-temperature-40061

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/nibe_heatpump/__init__.py", line 265, in _async_update_data
    return await self._async_update_data_internal()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/nibe_heatpump/__init__.py", line 287, in _async_update_data_internal
    async for data in self.connection.read_coils(_get_coils()):
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/__init__.py", line 43, in read_coils
    yield await self.read_coil(coil, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/modbus.py", line 136, in read_coil
    coil_data = self.coil_encoder.decode(coil, encode_u16_list(result))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/encoders.py", line 74, in decode
    raise DecodeException(
nibe.exceptions.DecodeException: Failed to decode start-temperature-hw-low-temperature-40061 coil from raw: 1400, exception: Raw value 20 is out of range for coil start-temperature-hw-low-temperature-40061

**Comment by elupus** [comment]
Ok. This is actually the built in conponent of home assistant. Not this custom component you are reporting on. I will try to look at it anyway.

**Comment by aigari** [comment]
I wonder if I'm the only one with this problem...
I reinstalled homeassistant from scratch and the Nibe integration still doesn't work, so the problem can't be with my device.

**Comment by elupus** [comment]
Its just one of the entities you have enabled. Just disable: start-temperature-hw-low-temperature-40061 then it should work.

**Comment by aigari** [comment]
Thanks for thinking along... 
It sounds too complicated to me :)

All the other entities react the same when I enable them.

**Comment by elupus** [comment]
You enabled them once. Disable all entities again, then enable them one by one again.

**Comment by aigari** [comment]
This solved the problem :)
Thank you very much!

**Comment by terhafso** [comment]
I have the same issue, but can`t solved the problem as described above. The only massage i get is "could not configure" when i try to reload. It looks like everything else is found and is fine

**Comment by elupus** [comment]
> I have the same issue, but can`t solved the problem as described above. The only massage i get is "could not configure" when i try to reload. It looks like everything else is found and is fine

Check logs. But likely you need to update the nibe custom component.

**Comment by terhafso** [comment]
> > I have the same issue, but can`t solved the problem as described above. The only massage i get is "could not configure" when i try to reload. It looks like everything else is found and is fine
> 
> Check logs. But likely you need to update the nibe custom component.

Thank you, i did an update...well only manual and it did not work, but removed all and reinstalled with HACS and now it works fine :-) . Again thank you so much.

**Comment by enoch85** [comment]
Can be closed?
