### ISSUE TITLE
how to call hot water boost function from automation

### ISSUE THREAD

**Issue by BartJocque** [elupus/hass_nibe#186]
my apologies for the somewhat stupid question here.

but how to call the  hot water boost function from an automation ?

(there seems to be no documentation here on how to use this integration)

many thanks in advance

**Comment by elupus** [comment]
You change operation mode on the water heater entity. If you want to automate that you need to look at standard documentation. That said. I dont have premium, so i dont know if it works.

**Comment by BartJocque** [comment]
anyone here that has done this and can perhaps share the automation code here ?

**Comment by enoch85** [comment]
@BartJocque You could also use this integration (builds on hass_nibe) which does everything for you based on your settings: https://github.com/elden1337/hass-peaqhvac

**Comment by elupus** [comment]
I dont understand why that (hass-peaqhvac)  is not using the hass nibe project. Could have supplied fixes to this project to avoid code duplication and multiple solutions.

**Comment by elden1337** [comment]
> I dont understand why that (hass-peaqhvac)  is not using the hass nibe project. Could have supplied fixes to this project to avoid code duplication and multiple solutions.

Hi, we can absolutely discuss a colab! But yes, the usecase is merely that i'm piggybacking on the services to update when my services says go. 
Improvements are welcome however so if you should spot something, please reach out.
