### ISSUE TITLE
Can´t set temperature to Nibe from my Homassistant

### ISSUE THREAD

**Issue by Uffen2005** [elupus/hass_nibe#192]
![Skärmbild 2023-10-09 194853](https://github.com/elupus/hass_nibe/assets/26470631/2e244d4e-dea5-40fa-8f93-4faf29037d5f)

When i try to set temperature to my Nibe from my Home Assistant i got this message, se attached file.
What should i do to make this work again?

**Comment by elupus** [comment]
Re authorize and allow write access (remove / readd). You must be paying for uplink for it to work too.

**Comment by Uffen2005** [comment]
I have a valid subscribtion for Uplink and the integration worked perferctly until may. I have  reinstalled the integration but with the same result. I belive that the integration stoped to work  somtime in the summer after one of the HA updates. I haven´t used the integration during the summer and early autumn so i can´t say exactly when it stoped to work.

**Comment by elupus** [comment]
You selected the wire access checkbox?

**Comment by Uffen2005** [comment]
I reinstalled the integration and now it seems to work.

**Comment by elupus** [comment]
Good to hear!
