### ISSUE TITLE
Which naming standard does `enteties` get?

### ISSUE THREAD

**Issue by enoch85** [elupus/hass_nibe#195]
I'm using @elden1337 integration for controlling my F750. The other day we noticed that our entities are name differently, and his code assumes a certain naming convention for it to work.

So basically a simple question; which naming standard are used for entities with this integration? In my case, the specific entetiy that I'm talking about is named `water_heater.nibe_hot_water` and something else for @elden1337.

Thanks for a great integration!

**Comment by elden1337** [comment]
Found the history explaining the diff. You may close this one @elupus 

![image](https://github.com/elupus/hass_nibe/assets/22585518/9fe9422f-f93f-4151-8878-76392d741176)
