### ISSUE TITLE
Problem with thermostat component in Home Assistant 0.88

### ISSUE THREAD

**Issue by stphndrnd** [elupus/hass_nibe#20]
Just updated to Home Assistant 0.88 and get the following error 

* In the log
```
Your configuration contains extra keys that the platform does not support.
Please remove [name], [system], [current], [target].
```

* In the notify component
Your configuration contains extra keys that the platform does not support (but were silently accepted before 0.88). Please find and remove the following.This will become a breaking change.

- [name], [system], [current], [target].  (See /config/climate/house_thermostat.yaml, line 4). 
- [system], [parameter], [object_id], [data]. 
- [system], [parameter], [object_id], [data]. 
- [system], [parameter], [object_id], [data]. 

* My config house_thermostat.yaml
```
##
## Nibe thermostat for the full house
## Full details: https://github.com/elupus/hass_nibe
##
- platform: nibe
  name: house_thermostat
  system: !secret nibe_uplink_system
  current: 40033
  target: 47398
```

According to this https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html the Nibe custom component is rightfully coded but the way to configure the custom component entities is now different. It should be something in the main nibe component in the config. Something like
```
nibe:
  - climate: ...
```
Is that supported? If so, how should the yaml syntax look like?

**Comment by elupus** [comment]
Could you try 0.88.1. I think there was a bug in this for 0.88

**Comment by stphndrnd** [comment]
Tried. Still the same issue.

**Comment by elupus** [comment]
Ok.. Try the dev version instead. Posted in in the forum thread. You need to redo configuration since structure have changed.

**Comment by TorbjornZachrisson** [comment]
The dev version is working with 88.1. I get this error with Nibe F730. Maybe something wrong on Nibe side? WARNING (MainThread) [homeassistant.helpers.config_validation] Found invalid entity_id group.nibe_30876_, please update with group.nibe_30876. This will become a breaking change.

**Comment by elupus** [comment]
Weird. You must be getting a category that is empty. Maybe you could try the console version of nibeuplink pip package and see what data it is you are getting.

**Comment by TorbjornZachrisson** [comment]
I don´t get that to work... Replace my client id and secret below.

nibeuplink --client_id "XXX" --client_secret "YYY" --redirect_uri "https://iggelbo.duckdns.org/api/nibe/auth" --system "30876"
https://api.nibeuplink.com/oauth/authorize?response_type=code&client_id=XXX&redirect_uri=https%3A%2F%2Figgelbo.duckdns.org%2Fapi%2Fnibe%2Fauth&scope=READSYSTEM&state=1b91ff56a55f42659d7a1204c38469e8
Enter full redirect url: https://iggelbo.duckdns.org/api/nibe/auth
Traceback (most recent call last):
  File "/usr/local/bin/nibeuplink", line 11, in <module>
    sys.exit(main())
  File "/home/tozac/.local/lib/python3.6/site-packages/nibeuplink/console.py", line 126, in main
    loop.run_until_complete (run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/tozac/.local/lib/python3.6/site-packages/nibeuplink/console.py", line 82, in run
    await uplink.get_access_token(uplink.get_code_from_url(result))
  File "/home/tozac/.local/lib/python3.6/site-packages/nibeuplink/__init__.py", line 278, in get_code_from_url
    return query['code'][0]
KeyError: 'code'

Best regards
Z

**Comment by elupus** [comment]
You need to enter the url you got redirected too when you open the given api url and login. It should contain some more arguments in your url.

**Comment by nolenjohan** [comment]
Upgraded Hass.io to 0.88.1 (from 0.87.1) and got "Invalid config" and "The following components and platforms could not be set up: Nibe"
"Please check your config"

**Comment by elupus** [comment]
Yes, you need to switch to dev version. I will replace master branch soon.

Den tors 28 feb. 2019 10:49nolenjohan <notifications@github.com> skrev:

**Comment by nolenjohan** [comment]
As per Dev Readme, should this section not be part of configuration.yaml anymore?

    client_id: <client id from nibe uplink>
    client_secret: <client secret from nibe uplink>
    redirect_uri: <the redirect url you have entered at nibe uplink configuration>
    writeaccess: false # set to true to support climate write (needs new tokens)

Also, I have another Hass.io upgraded to 0.88.1 and there the Master Branch works fine...

**Comment by nolenjohan** [comment]
Reverted back to Master Branch and now it works, though with a "Config Warning" that I can dismiss. I assume that config is being fixed in the coming release? Thanks!
![image](https://user-images.githubusercontent.com/34334118/53571263-c177c400-3b68-11e9-8b6b-70eead259510.png)

**Comment by elupus** [comment]
It won't be fixed. Dev branch will be used. Those fields are set during config flow.

**Comment by nolenjohan** [comment]
Added minimal config in configuration.yaml, added the content of "hass_nibe-dev" to "\config\custom_components\nibe" - rebooted HA.

Nibe no longer visible, no request to config anything showed up. Something more that needs to changed? I renamed the "\config\nibe.json" as well, no difference.
In Lovelace the "icon" is there, but no entities exists:
![image](https://user-images.githubusercontent.com/34334118/53578480-140cac80-3b78-11e9-92f5-2157ed53acde.png)

**Comment by elupus** [comment]
Go to config integration page and select nibe uplink.

**Comment by fondberg** [comment]
I believe there is an issue between with hassio 0.88.1 and the dev version because there are more people where it doesn't work.

Do you also see the same in the log as described [here in the end](https://community.home-assistant.io/t/nibe-uplink-api-component/18173/267)?

**Comment by fondberg** [comment]
@elupus it won't show up because of the issue with Hassio 0.88.1 and the dev version 
```
Invalid config for [nibe]: [climates] is an invalid option for [nibe]. Check: nibe->nibe->systems->0->units->0->climates. (See /config/configuration.yaml, line xxx). Please check the docs at https://home-assistant.io/components/nibe/
```

**Comment by elupus** [comment]
Climates is no long a sub key of unit. It's on system level now.

**Comment by nolenjohan** [comment]
Thanks @elupus 
Now I get it working in Lovelace, but if I turn to States UI there is no "Nibe icon" on top.
Some binary_sensors are missing now, see picture, is that since I have not added anything under "sensors:" in the config? In such case, how to add those missing binary_sensors?
![image](https://user-images.githubusercontent.com/34334118/53579607-238cf500-3b7a-11e9-9c80-d7cc8d9671b3.png)

**Comment by elupus** [comment]
The view was removed. You can add your own group for that. The missing binary sensors are now standard sensors. Saw no reason for having those become binary sensors.

**Comment by elupus** [comment]
To fix your lovelace view, you can just change binary_sensor.* to sensor.*

**Comment by nolenjohan** [comment]
Thanks!
So no automatically created view in States UI?
I have to add a view and manually create the different groups with sensors within that view?

**Comment by fondberg** [comment]
Works like charm! Great job!

**Comment by nolenjohan** [comment]
sensor.nibe_XXXXX_0 seems to have been removed, correct? The previously used "Version" that didn't show any version...

**Comment by elupus** [comment]
So far the groups for the categories remain. But lovelace have no way to display groups natively. So manual it is for now. Wish it can support some type of entity filter setup later.

**Comment by elupus** [comment]
Yes. Parameter 0 was just not working.

**Comment by nolenjohan** [comment]
I found (so far) two new sensors, "S1 Room" and "S1 Supply", what are those sensors really showing? 
![image](https://user-images.githubusercontent.com/34334118/53580457-f7727380-3b7b-11e9-9e10-1852aa270359.png)

**Comment by nolenjohan** [comment]
I don't get it how to add the view for States UI? (since I prefer that view for now in favour of LL)
Name the view anything?
Name of the mdi-icon?
What groups and sensors to add to the view?

![image](https://user-images.githubusercontent.com/34334118/53581203-6a301e80-3b7d-11e9-8cfc-b517ec35474f.png)

**Comment by nolenjohan** [comment]
OK, added the Nibe Groups, though, missing "Compressor" and "Brine Pump" groups, not existing in the entity list.

**Comment by nolenjohan** [comment]
Created my own groups for "Compressor" and "Brine Pump" and added the relevant sensors, so now it's fully functional both with Lovelace and States UI
Thanks!

**Comment by elupus** [comment]
S1 Room is your indoor room termometer and the target temperature the pump is targetting.

S1 Supply is the water supply to your heating radiators/floor and the target temperature the pump is calculating based on outdoor sensor and termostat. 

Off means it's not currently producing heat. It should toggle on/off when pump starts running to heat up.

Did you add the water_heater tag too? The you get the hot water heater tank info to and ability to set temporary boost.

**Comment by stphndrnd** [comment]
So I tried the dev branch. I got the Nibe option in the config/integration menu once. Then never again. It was complaining about the new config structure when I configured the Nibe component in the integration menu. I removed the integration done, removed the nibe.json in the /config directory. restarted HA and now I don't see any integration menu for Nibe. Upgraded to Hassio 0.88.2 - nothing.

this is my nibe config
```
systems:
  - system: !secret nibe_uplink_system
    units:
    - unit: 0
      categories: true
      statuses: true
      switches:
        - hot_water_boost
        - ventilation_boost
      climates: true
      water_heaters: true
```
This is the message I get in the logs
```
2019-02-28 21:00:26 WARNING (MainThread) [homeassistant.loader] You are using a custom component for nibe which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-02-28 21:00:41 ERROR (MainThread) [homeassistant.config] Invalid config for [nibe]: [switches] is an invalid option for [nibe]. Check: nibe->nibe->systems->0->units->0->switches. (See /config/configuration.yaml, line 98). Please check the docs at https://home-assistant.io/components/nibe/
2019-02-28 21:00:41 ERROR (MainThread) [homeassistant.setup] Setup failed for nibe: Invalid config.
```
I am not getting something. What did I miss?

**Comment by elupus** [comment]
switches, climates, water_heater are indented one step too much. They should be on system level.

**Comment by elupus** [comment]
I've merged dev into master so technically this issue is closed. But i'll wait till you setup is working @stphndrnd

**Comment by nolenjohan** [comment]
Suddenly the missing two groups appeared, working fine!
![image](https://user-images.githubusercontent.com/34334118/53599242-0589b980-3ba7-11e9-881b-cff6573df4d8.png)

**Comment by nolenjohan** [comment]
One final thing:
How to get the icon also in States UI?
icon: mdi:? <- any suggestion?

**Comment by stphndrnd** [comment]
I got now the time to test. It works very well!
The S1 supply thermostat should actually be 2 sensor according to me: one binary to understand if it produces warm water or not and one to know the current water temperature. As a thermostat you can now set the target temperature which ideally to ensure the correct function of the pump should only be done in the warming curve setup in the pump. Any motivation behind the choice of a thermostat entity for this?

The warm water boost works also very well. The roll-up menu is however very technical and in english only. Any chance one can customize it to the local language?

**Comment by elupus** [comment]
S1 Supply will go to off state when producing hot water. So this can be used as a binary sensor. I think it looks nice as a climate sensor. It also combines several parameters. I have no indoor temp sensor, so S1 Room is not available. Only adjust that can be done is offset and curve.

**Comment by MichaelRoxin** [comment]
I have tried and tried to  get this to work but something goes wrong. 

I have downloaded the zip file and copied the files to /custom_components/nibe

My code looks like 

`nibe:
  systems:
    - system: xxxx
      units:
      - unit: 0
        categories: true
        statuses: true
      switches:
      - hot_water_boost
      - ventilation_boost
      climates: true
      water_heaters: true`

check config looks like

Invalid config for [nibe]: expected int for dictionary value @ data['nibe']['systems'][0]['system']. Got xxx
extra keys not allowed @ data['nibe']['systems'][0]['climates']. Got True
extra keys not allowed @ data['nibe']['systems'][0]['switches']. Got ['hot_water_boost', 'ventilation_boost']
extra keys not allowed @ data['nibe']['systems'][0]['water_heaters']. Got True
required key not provided @ data['nibe']['client_id']. Got None
required key not provided @ data['nibe']['client_secret']. Got None
required key not provided @ data['nibe']['redirect_uri']. Got None. (See /config/configuration.yaml, line 637). Please check the docs at https://home-assistant.io/components/nibe/

Shall xxx is as I understand the idintifier from the nibe uplink webpage? Or shall it be the numer of my system. 

Can someone please help me as I have been trying alot to understand how to do this.

**Comment by elupus** [comment]
Looks like you have an old version of the component?

**Comment by elupus** [comment]
You have an invalid systemid. You can find that out by removing the systems list completely to begin with. You should get a notification about available system.

**Comment by MichaelRoxin** [comment]
Okej, thanks for the answer but it´s like you are from another planet :) 

I have downloaded the files (zip.file) and put all *.py files in custom_components/nibe and tried the minimal configuration. 

Can´t find any thing with nibe or climate or nothing. 

I see above that some are talking about intregrations in gui. I have no Nibe there.

**Comment by elupus** [comment]
The minimum config still need you to enter a system identifier. Since you put xxx there it won't work.

Also like I said. Seems you have an old version (zip file). Please re-download.

**Comment by MichaelRoxin** [comment]
I have put the 5 didget number from the Nibe Uplink webpage URL. 

Vänligen Michael Roxin

**Comment by MichaelRoxin** [comment]
Now I have once again put the files in custom_components/nibe and put in minimal configuration with my 5 digits system number. 

Checks ok but efter reboot I don't get any sensors, climate or nothing. No trace of Nibe except in the log. 019-03-06 21:42:30 WARNING (MainThread) [homeassistant.loader] You are using a custom component for nibe which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

**Comment by elupus** [comment]
Good. Then go into configuration / integrations to set it up.

**Comment by MichaelRoxin** [comment]
I don’t have an option for Nibe there. 

Vänligen Michael Roxin

**Comment by elupus** [comment]
I really don't know what is going on then. It should have been right at the bottom. Are you running hassio or standalone?

I'd hassio could you try on a standard computer instead? Windows, Linux or osx.

**Comment by MichaelRoxin** [comment]
IM running Hassio. 

What do you mean with try a sand alone? 

I had this Working before but it Was a while ago. 

So after adding the code in configurations you mean that i Will get the possibillity to add via integration page. So there is where i add My id from api page and sectret. 

Vänligen Michael Roxin

**Comment by elupus** [comment]
Standalone as in on a normal computer. Yes it should show up on integration page and that is where you set client ID. Usually ends up as the last item of the 20 or so already there.

**Comment by MichaelRoxin** [comment]
I have located the objekt at the integration page. 

It Was down below and with no titel. 

When i try to add id and sectret it do not work. 

Do it matter if i use the Duck DNS or internal adress? 

If i pastle the URL from Nibe api page and try to Open it. It says ”massage”: ”state missing in URL” 

Can this be something?

Vänligen Michael Roxin

**Comment by elupus** [comment]
You need to paste only the code part of the page you end up on after accepting access on nibe homepage. It's a bit unintuitive. I suppose I should allow paste of url too. 

Make sure your redirect url was in the given format. Just change of hostname/port to duckdns name or your internal ip of the device.

**Comment by MichaelRoxin** [comment]
This i can’t understand how you mean? 

Is it possible to explain more simple?

Vänligen Michael Roxin

**Comment by MichaelRoxin** [comment]
All of you seem like super computer Bill Gates types 😉

IM a Lawyer so instructions sometimes are hard to understand. 

Vänligen Michael Roxin

**Comment by elupus** [comment]
You should end up on a page with ONLY:
{message="bla bla bla" code="longstringoflettersandnumbers"} efter you
followed the Authorize link.

It's the part for code inside the "" you need to copy back into the code
input dialog.

Den tors 7 mars 2019 12:07MichaelRoxin <notifications@github.com> skrev:

**Comment by MichaelRoxin** [comment]
So the steps are not
1. Put in id (from Nibe api page)
2. Put in secret (from Nibe api page)

If not then i don’t understand how to do this. The instructions are not so good. 

Vänligen Michael Roxin

**Comment by elupus** [comment]
That first. Then press submit. At the page with the code enter box, press
the link authorize. Which will open a new tab/window. Accept the access on
nibes page. It will then go to the page I mentioned before.

**Comment by MichaelRoxin** [comment]
Okej but can’t get to the page after i have put in id and secret. 

Vänligen Michael Roxin

**Comment by elupus** [comment]
Why?

Den tors 7 mars 2019 13:01MichaelRoxin <notifications@github.com> skrev:

**Comment by MichaelRoxin** [comment]
I tried in the iOS app but do not work. Shall try on chrome back Home tonight. 



Vänligen Michael Roxin

**Comment by MichaelRoxin** [comment]
No I have tried. When I put in id and secret I get another window with one line. But no more info. What to put there?

**Comment by elupus** [comment]
There should be instructions on that page. Wait, you have missed to copy one folder?! There is a folder called ".translations" notice the beginning dot/period. That is why you get no text.

**Comment by MichaelRoxin** [comment]
the folder is not part of the zip file and I can´t create a folder that starts with a dot.

**Comment by elupus** [comment]
Files starting with period are hidden files on osx/Linux systems. You will
se it with "ls -a" in a terminal.

Den tors 7 mars 2019 17:49MichaelRoxin <notifications@github.com> skrev:

**Comment by MichaelRoxin** [comment]
Okej but how should i do to create the folder in Hassio so i see the text. 

Vänligen Michael Roxin

**Comment by elupus** [comment]
You don't create it. You copy the folder from the zip file. Or extract the
zip direct to where it should be.

Den tors 7 mars 2019 18:49MichaelRoxin <notifications@github.com> skrev:

**Comment by MichaelRoxin** [comment]
I run mac so the zip folder looks like a regular folder when i downlod it and inside there are only the files not the folder.

Tips?

**Comment by elupus** [comment]
It's there. If you open a terminal and do the command I told you you'll see
it. Or Google on how to see hidden files on Mac.

Den tors 7 mars 2019 19:12MichaelRoxin <notifications@github.com> skrev:

**Comment by MichaelRoxin** [comment]
Working and I get a water heater thats it. So I will try the more advanced config - will I have to delete the integration and connect agin or can I simply change just in configurations.yaml and reboot?

Thanks for all help.

**Comment by MichaelRoxin** [comment]
The following component could not be setup

nibe climate

Why?

All the other sensors and stuff are working now. BIG THANKS

**Comment by elupus** [comment]
Now you only need to modify config. You can have been hit with the issue
#23. I may need to release a new version to get it working properly on
hassio. Check log for same error as in referenced issue.

Den tors 7 mars 2019 21:24MichaelRoxin <notifications@github.com> skrev:

**Comment by elupus** [comment]
This issue is solved. I'll close it. Also a fix for python version 3.5 (hassio) has been pushed. So can be worth updating if you have issues.

**Comment by MichaelRoxin** [comment]
Okej so i just download the files again and reastart and climate Will work?

Vänligen Michael Roxin

**Comment by MichaelRoxin** [comment]
Hi

I have downloaded the new zip folder and copied to custom_components/nibe just now and reboot. 

Still no climate. 

Where do I find the fix? 

Update to latest hassio? 0.890 maybe?

Regards

**Comment by elupus** [comment]
It should i think. At least if you have errors in log.

Den lör 9 mars 2019 07:31MichaelRoxin <notifications@github.com> skrev:

**Comment by MichaelRoxin** [comment]
When Will the climate work?

I Can”t see the same errors  

Vänligen Michael Roxin

**Comment by elupus** [comment]
When it is fixed...

**Comment by elupus** [comment]
Just checked. Climate does work. you need hass 0.89 thou.

**Comment by MichaelRoxin** [comment]
Great Will try to update then and Hope it Will work. 

Thanks for the help. 

Vänligen Michael Roxin

**Comment by MichaelRoxin** [comment]
Did the update. 

Got three climate
Climate.kitchen_thermostat
Climate.nibe4855_s1_room - unavaible 
Climate.nibe48554_s1_supply (shows heat)

What do they mean? I have more then One thermostat (i think) One in Evert room but unsure if they are part of Nibe smart Home. 

I don’t understand these entities? Can you help me explain?


Vänligen Michael Roxin

**Comment by elupus** [comment]
@MichaelRoxin 
room one unavailable mean you have no indoor temperature sensor on your pump
supply is temperature going to your radiators/floors
kitchen_thermostat is something you created. The system does not display any smart home thermostats linked by other means.

**Comment by elupus** [comment]
@MichaelRoxin this issue is closed. if you have issues with the plugin. please open new issues

**Comment by MichaelRoxin** [comment]
True. I have no indoor temp. 

Kitchen thermostat where did i create it then? 

Vänligen Michael Roxin

**Comment by MichaelRoxin** [comment]
Okej sorry. 

Vänligen Michael Roxin
