### ISSUE TITLE
Only some questions

### ISSUE THREAD

**Issue by Manhem** [elupus/hass_nibe#201]
Hi.
I have just reinstall my Home Assistant machine and after that I get some strange things in Nibe add on.
Before I reinstall it I have lot of values that I could use.
For example: Int. el.add Power, Tot. op. time add, Stop Temperature Additive, Allow Additive Heating and many more.

Now everything is grayed out and not reachable any more.

Everything, HomeAssistant, HACS, Nibe and all other add ons, are up to date.

I'm using ESPhome and a homemade interface to the Nibe Heatpump F1145.

Thanks for a great addon

**Comment by elupus** [comment]
Start with making sure you have the latest hass_nibe version.

**Comment by Manhem** [comment]
Hi.
I don't know where I can find your software version number.
The only thing I found is.
Unit information: 8224

I have downloaded your software and put in the Nibe folder.

**Comment by elupus** [comment]
Yes,.but when did you download it. If it was more than a few days ago download it again from this page or preferably install it by using HACS so its kept updated.

**Comment by Manhem** [comment]
I downloaded this morning.
I use HACS and Nibe Uplink has version 1.6.1.

**Comment by elupus** [comment]
Then have a look at the log in home assistant and check for errors.

**Comment by Manhem** [comment]
Hi.
I think I found the problem.
It seems like my ESP has change ip address.
More tests must be done, but so far I get in values.
Thanks for your help. I hope this has solved the problem.

**Comment by elupus** [comment]
This project has nothing to do with the built in integration in HA. But good that you found out what was going on.
