### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by Nikojoel** [elupus/hass_nibe#206]
Hi! Complete newbie to Home Assistant here trying to setup the Uplink integration for my F470 pump. I can't seem to find the Nibe Uplink Heat Pumps integration listed in the integrations search. I've got HACS installed too. Any help? Thanks in advance!
<img width="508" alt="image" src="https://github.com/elupus/hass_nibe/assets/45162563/7083157a-e3dc-4cc9-9dfa-c2f2d775c6c1">

**Comment by elupus** [comment]
You need to add a repository in hacs

**Comment by Nikojoel** [comment]
<img width="672" alt="image" src="https://github.com/elupus/hass_nibe/assets/45162563/6068df6c-a1b3-4a37-bc0d-8b43a53c7d2c">

I've searched from here as well. Nothing comes up. Is there a direct link for the repo?

**Comment by Nikojoel** [comment]
Oh god I'm dumb. I've just read the instructions again and figured it out
