### ISSUE TITLE
Strange behavier

### ISSUE THREAD

**Issue by Manhem** [elupus/hass_nibe#209]
I have a strange behavier with Home Assistant and Nibe.
I have change the IP addresses to the HomeAssistant and after that Nibe is working strange.
Think I have missed something but don't know what.

I have put in the new ip to my HA machine and also a static ip for the Nibe Modbus unit in the ESPhome Nibe yaml.
Made a new clean installation on the ESP8266. 

My pump is connectet by Modbus to a ESP8266.

The things is that some of the values are shown but some are not (they are all grayed out)

For ex. I can see Outdoor temperature, HW Load and more
But Degree Minutes, Min Supply System, Language and more are all grey.

Before I change the ip address, all was working.

HomeAssistant, ESPhome are all the latest version, updated today.

Any clue what I have missed?

**Comment by Manhem** [comment]
I have solved the problem.
Something went wrong when I installed a new version.

To solve the problem I delete the whole installation of Nibe and after that I installed from scratch again.

Now everything is back.

**Comment by elupus** [comment]
Ok. If you figure out what went wrong post back.
