### ISSUE TITLE
Possible run out of service? Depreciated Integrations

### ISSUE THREAD

**Issue by Max220729** [elupus/hass_nibe#211]
Dear folks, got recently those warnings:
<img width="1694" alt="Bildschirmfoto 2024-04-21 um 19 29 53" src="https://github.com/elupus/hass_nibe/assets/166832462/a33a9c77-8b1b-42f8-82d6-e959a25c5d1f">

Anybody an idea what can be done?

**Comment by elupus** [comment]
Needs to be fixed. No major rush though. I have a year to fix it :)

**Comment by elupus** [comment]
Fixed
