### ISSUE TITLE
initial API authorisation not working after heatpump migration to myuplink.com

### ISSUE THREAD

**Issue by BartJocque** [elupus/hass_nibe#215]
after updating my heatpump to the latest firmware it was automatically migrated to the new myuplink portal

but now the initial API authorisarion is not working anymore towards https://dev.myuplink.com/login

this is because the integration is still pointing to old portal for the initial auth

is it planned to correct this ?

**Comment by elupus** [comment]
Nope. Myuplink is supported by home assistant directly. This integration will soon not be maintained.

**Comment by BartJocque** [comment]
ok thanks for the update
