### ISSUE TITLE
Measurement for energy consumption or power per heating/cooling/hot_water

### ISSUE THREAD

**Issue by BjRnJ** [elupus/hass_nibe#217]
First of all: great HASS integration!

**Goal**
I want to monitor the energy consumption of my VVM 225 heat pump and be able to specify the amount of energy used for heating, cooling and hot water.

**Findings / tried so far**
- Started with keys 44302, 44300 and 44298 as energy [kWh] for heating, cooling and hot water, but found out these are _produced_ energy as also discussed in https://github.com/elupus/hass_nibe/issues/103. See image below for confirmation, the sum of these sensors are higher than grid energy consumption. I am confused however that https://github.com/elupus/hass_nibe/pull/142 describes them as energy consumption
- I can calculate the power based on currents (40079, 40081, 40083)
- Hoped to then get the Priority. Tried the "Nibe VVM 225 Status compressor (EB101)" entity to label if energy is for heating, cooling or hot water, but as far as I understand this is compressor ON/OFF only. 
- Found discussions on Priority sensor on https://github.com/elupus/hass_nibe/issues/194 (but S-series) and https://github.com/elupus/hass_nibe/issues/17, but I am unable to find a Priority sensor in Home Assistant or the current integration source code. Moreover, at OpenHAB I was only able to find a priority key on [direct Modbus documentation](https://www.openhab.org/addons/bindings/nibeheatpump/) for Nibe, not for [Uplink](https://www.openhab.org/addons/bindings/nibeuplink/)
- In `climate.py`, I did find `HVACAction` translating status into heating or cooling, but I don't see this translating to a sensor / measurement. 

**Question**
What am I missing? How can I either get the energy consumption per heating/cooling/hot_water directly, or get the Priority in Home Assistant? (which is a default 'status' card on the myUplink dashboard in both app and [web portal](https://myuplink.com/) )

<img width="560" alt="Screenshot 2024-10-24 at 10 03 25" src="https://github.com/user-attachments/assets/5f547f14-9fa8-42a2-83ea-22a84e7c9ec0">

**Comment by elupus** [comment]
43986 is the prio sensor

**Comment by BjRnJ** [comment]
Thanks for your response! 43986 doesn't seem to be available as diagnostic entity within Home Assistant. Or do you mean a diagnostics function from Nibe / myUplink?

I've made `/v3/devices/{deviceId}/points` and `/v3/devices/{deviceId}/points` calls to my system using the [Swagger UI](https://api.myuplink.com/swagger/index.html) provided by Nibe, and 43986 as well as any form of Priority is not in the return message.

**Comment by elupus** [comment]
Hmm. This is the old deprecated project for nibeuplink. MyUplink is part of home assistant and it can only expose what myuplink exposes. So can't really help you there.

I initially thought you where using the direct connection method with a nibegw device that os also supported by ha, that would have exposed that parameter.

That said i would assume prio should be available somewhere in myuplink api i think.

**Comment by BjRnJ** [comment]
Thanks again @elupus. I'll try to reach out to Nibe / MyUplink to see if they can help extending their API, and otherwise reconsider adding hardware and use NibeGW.

**Comment by imist** [comment]
FWIW: Priority is available in the standard myUplink integration, at least for my F750:

![IMG_0006](https://github.com/user-attachments/assets/6e3c5971-14b2-4aa0-8a88-c6b96a9b2c56)
