### ISSUE TITLE
Fan speed synchronization

### ISSUE THREAD

**Issue by Funkenschuhster** [elupus/hass_nibe#218]
Hi,

any idea how to keep the fan speed of my venting system synced? 
Its a big deal, if i put one fan to high level without changing the other one. This can damage the insulation forever.

**Comment by elupus** [comment]
Eh?! This issue market no sense.

**Comment by Funkenschuhster** [comment]
New attempt with translator:

It's about the fans of the ventilation system. There must be a way to adjust the setpoints at the same time. If you accidentally change the speed of just one fan, this can cause immense damage, depending on the speed difference. 

For example:
Imagine that the exhaust air is running at 20% and the supply air is requested at 100%. In this case, the air pressure in the house rises rapidly and the adhesive seams of the vapor barrier can come loose. The vapor barrier is a bonded foil behind the walls in the roof. Once it is damaged, all the walls in the roof must be opened up again.

Its about these parameters:
```
  - entity: number.ers_1_exhaust_fan_speed_1_48856
    name: ERS 1 Exhaust Fan speed 1
  - entity: number.ers_1_exhaust_fan_speed_2_48855
    name: ERS 1 Exhaust Fan speed 2
  - entity: number.ers_1_exhaust_fan_speed_3_48854
    name: ERS 1 Exhaust Fan speed 3
  - entity: number.ers_1_exhaust_fan_speed_4_48853
    name: ERS 1 Exhaust Fan speed 4
  - entity: number.ers_1_exhaust_fan_speed_normal_48857
    name: ERS 1 Exhaust Fan speed normal
  - entity: number.ers_1_supply_fan_speed_1_48899
    name: ERS 1 Supply Fan speed 1
  - entity: number.ers_1_supply_fan_speed_2_48898
    name: ERS 1 Supply Fan speed 2
  - entity: number.ers_1_supply_fan_speed_3_48897
    name: ERS 1 Supply Fan speed 3
  - entity: number.ers_1_supply_fan_speed_4_48896
    name: ERS 1 Supply Fan speed 4
  - entity: number.ers_1_supply_fan_speed_normal_48900
    name: ERS 1 Supply Fan speed normal
```

As an example:
If I change the supply air from 20% to 40%, then the exhaust air must also be set to 40% immediately.
```
  - entity: number.ers_1_exhaust_fan_speed_1_48856
  - entity: number.ers_1_supply_fan_speed_1_48899
```

**Comment by elupus** [comment]
Okey but what does this have to do with this deprecated addon that uses nibeuplink which is no longer available... https://www.nibeuplink.com/

That sound like some type of automation 
problem with home assistant that you need to solve when you automate these thibgs.

**Comment by Funkenschuhster** [comment]
Okay got it, wrong project, wrong platform. Sorry, I never used git. Where to ask these questions?

**Comment by elupus** [comment]
Github is for issues bugs in the code. What you are asking is about how to automate things in home assistant. Has nothing to do with a specific integration. Community forums is (or the discord chats) is where general support things are handled.

**Comment by imist** [comment]
Start here [https://www.home-assistant.io/help/](https://www.home-assistant.io/help/) for general help on Home Assistant.
