### ISSUE TITLE
Better documentation on setup

### ISSUE THREAD

**Issue by ChristophLindemann** [elupus/hass_nibe#24]
Could you please expand the setup/configuration documentation (and some UI screenshots of working system)

It does not explain where to configure authorization values. It just mentions, that one shouldn’t take note of them.

Also the the config examples expect you to put a system identifier? Where to get that one? From the config errors in log, I gather that it is some integer. Is it the ID from the NIBE Uplink URL?

Currently I have it installed, and get no errors, but I do not see any sensors or devices in HA.

So I am kind of lost (without diving into the code) where I might have done something wrong, or even what to expect when it works :)

So a small expansion on the documentation would be greatly appreciated.

**Comment by elupus** [comment]
Did you do the config on integrations page? 

PS. Once you get it working feel free to provide additional documentation. This is a spare time thing.

**Comment by ChristophLindemann** [comment]
I don't think I found anything NIBE related on the integration page. But I may have missed it.

I will be happy to write some documentation and create a PR, once I have it set up and working, Right now I am stuck ;) I will have a look at it again in the weekend.

**Comment by elupus** [comment]
Just add a empty "nibe:" clause to your config to start with. Once it's setup you should get a list of systems to expand config with.

**Comment by ChristophLindemann** [comment]
> Just add a empty "nibe:" clause

Yeay, that did the trick!

**Comment by runevad** [comment]
I can give it a go with some pictures and more text if you want. The more people using this great integration the more questions are going arise.

**Comment by runevad** [comment]
Anyone else want to contribute and read through the pull request? https://github.com/elupus/hass_nibe/pull/25

**Comment by elupus** [comment]
I'll close this now that the updated documentation is added.
