### ISSUE TITLE
Smart Home mode

### ISSUE THREAD

**Issue by fondberg** [elupus/hass_nibe#27]
First, awesome work!
I updated this morning and thought I would get smart home mode switch with your recent change. Do I need to remove nibe.json and restart HA and redo the configuration or how do I get it to show up?

**Comment by elupus** [comment]
There is no switch. There is only a service for now.

**Comment by fondberg** [comment]
I see. Thanks. Does it take any parameters?

**Comment by bohtho** [comment]
`
set_smarthome_mode:
  description: Set system into a given smarthome mode.
  fields:
    system: {description: System identifcation to send command to., example: "12345"}
    mode: {description: "Mode to select. Can be DEFAULT_OPERATION, AWAY_FROM_HOME or VACATION", example: "DEFAULT_OPERATION"}`

**Comment by rostikk80** [comment]
How about reading smart home mode? GET api/v1/systems/{systemId}/smarthome/mode
Is there an entity for it?

**Comment by rostikk80** [comment]
> How about reading smart home mode? GET api/v1/systems/{systemId}/smarthome/mode
> Is there an entity for it?

Bump

**Comment by elupus** [comment]
Feel free to implement and give me a pull request :)

**Comment by mthornhill** [comment]
https://github.com/elupus/hass_nibe/pull/82

**Comment by sami-one** [comment]
Could someone show a working yaml for for set_smarthome_mode service as button? I'm new to home assistant and would like to make buttons to manually set VACATION mode on.

**Comment by elupus** [comment]
There is a switch for it already. Just make sure you are up-to-date.

**Comment by sami-one** [comment]
> There is a switch for it already. Just make sure you are up-to-date.
Am I even near at getting this to work? The ui shows the switch below. (id number sensored with XXX): 

service: switch.turn_on
data: {}
target:
  entity_id: switch.nibe_XXXXXX_XXXXX

this results "Failed to call service switch.turn_on. Unknown error". 
And from the logs (part of url sensored with XXXXXX):
 Error handling message: Unknown error (unknown_error)
aiohttp.client_exceptions.ClientResponseError: 400, message="{'httpStatusCode': 400, 'errorCode': 1, 'timestamp': '2022-06-10T11:52:03.9959677Z', 'details': ['Error 14:  48043'], 'data': None}", url=URL('https://api.nibeuplink.com/api/v1/systems/XXXXXX/parameters')

Guidance would be appreciated
