### ISSUE TITLE
Read (or even set) parameter for the chosen heating curve ?

### ISSUE THREAD

**Issue by bohtho** [elupus/hass_nibe#28]
Do you, or anyone, know if there's an existing entitiy or a possible parameter where the chosen heating curve on the NIBE can be read (or even written to) ?

**Comment by elupus** [comment]
The offset is controlled by the climate supply entity. The angle can't be controlled by standard entities. But should be possible by set_parameter service. If you look at api.nibeuplink.com and under parameters. The curve parameters are there.

**Comment by bohtho** [comment]
Ah, yes, I see 47011 is "The parallell adjustment for climate system 1 when heating", but as you say I don't know where the angle is stored.

**Comment by bohtho** [comment]
Apparently 47007 is "S1 Heat curve 1" according to https://github.com/openhab/openhab1-addons/wiki/Nibe-Heat-Pump-Binding.

So these parameters that aren't entities can just be added in the config with the number code ?

**Comment by elupus** [comment]
For reading yes. For writing no. 
There are sadly no platform entities in HA for input values. You have to add your own input_number entity and hook a automation to it calling the set_parameter service.
