### ISSUE TITLE
Write target temperature

### ISSUE THREAD

**Issue by iCarl** [elupus/hass_nibe#3]
Are you able to write values to Nibe Uplink?
For example if I'd like to set at target temperature.

**Comment by elupus** [comment]
Not at the moment. I don't have payed account. A patch would be accepted
thou.

Den 1 nov. 2017 12:52 skrev "iCarl" <notifications@github.com>:

**Comment by iCarl** [comment]
But would it be possible if I'm using a paid account?

**Comment by elupus** [comment]
The nibe API should allow it. But no support in this plugin at the moment.

Den 1 nov. 2017 13:13 skrev "iCarl" <notifications@github.com>:

**Comment by elupus** [comment]
There is a branch (module) with theoretical write support for target temperature on climate system.
