### ISSUE TITLE
Is 67980 S1 Supply writeable directly ?

### ISSUE THREAD

**Issue by bohtho** [elupus/hass_nibe#30]
... instead of indirectly controlling it through S1 Room and the smart set_thermostat service ?

The case is that I already have a Siemens heating circuit control system connected to thermostats and radiator actuators. From this I get a "demanded" flow temperature. Instead of manipulating the loading of a fake room thermostat through the set_thermostat service to S1 Room to align the Siemens system with the NIBEs Calculated Supply Temperature (S1 Supply), could I write the demand to it directly ?

Also, where does it get all the max and min values in the entity ? I'm not currently sharing valve data anymore and only one "fake room". My 67980 S1 Supply:

```
{
  "current_temperature": 43.3,
  "min_temp": 33.6,
  "max_temp": 53.6,
  "temperature": 49.6,
  "target_temp_step": 1,
  "status": "DONE",
  "pump_speed_heating_medium": 0,
  "supply_temp": 43.3,
  "calc_supply_temp_heat": 49.6,
  "calc_supply_temp_cool": 22.7,
  "offset_heat": 6,
  "offset_cool": 0,
  "external_adjustment_active": true,
  "friendly_name": "S1 Supply",
  "supported_features": 1
}
```

**Comment by elupus** [comment]
Nah supply modifies the offset of the curve.  Min max is calculated based on current value plus maximum possible offset.

**Comment by bohtho** [comment]
...and also accounts deviation between setpoints and temperatures of smart thermostats.

Ok, would turning off Degree Minutes in the Service menu of the VVM320, and just going with my own compressor curve have any effect and/or stop it from calculating S1 Supply from the chosen heating curve and offset?

**Comment by elupus** [comment]
That would be a feature of the pump. The code for the supply climate is always just controlling heat curve offset. It does some magic to display as absolute temp.

I suppose there might be some debug mode of the pumps to bypass heat curve. You'd need to chat with nibe on that. If you find it, there is a parameter for it and you are allowed to update it by nibe, you should be able to use the service to set a specific parameter.

Hmm.. that said you could probably play games with the S1 supply and readjust it every time it changes to your wanted setpoint. With a home Assistant automation. There is a limit to adjust of +- 10 degrees thou so heat curve must be reasonable correct.

**Comment by bohtho** [comment]
Maybe a better idea to manipulate the heat curve (the parallel) then, which stays at the set level. Only problem is that it seems the heat pump takes a lot of time to adjust to a new parallel, and it won’t be as exact.

**Comment by bohtho** [comment]
Why the error only saying "mode" which I get when trying to set the heating curve parallel on parameter 47011 with this JSON from the dev-service page (real system code used):
```
{
    "system": 6xxxx,
    "parameter": 47011,
    "value": 2
}
```

**Comment by elupus** [comment]
What do you mean mode? I don't remember but maybe the value need to be a string.

**Comment by bohtho** [comment]
You are right about it needing to be a string. But still this cryptic error message just saying "mode". I know I have the right scope. It's probably out of your hands if it's an error message from Nibe but has anyone else got set_parameter to work ?

**Comment by elupus** [comment]
I still don't understand. "mode", is that from the log or from gui or what?

**Comment by bohtho** [comment]
```
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.6.3/envs/homeassistant-3.6.3/lib/python3.6/site-packages/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/home/homeassistant/.pyenv/versions/3.6.3/envs/homeassistant-3.6.3/lib/python3.6/site-packages/homeassistant/core.py", line 1133, in async_call
    self._execute_service(handler, service_call))
  File "/home/homeassistant/.pyenv/versions/3.6.3/envs/homeassistant-3.6.3/lib/python3.6/site-packages/homeassistant/core.py", line 1155, in _execute_service
    await handler.func(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/nibe/services.py", line 27, in set_smarthome_mode
    call.data['mode']
KeyError: 'mode'
```

It refers to `set_smarthome_mode` but I am calling `set_parameter`.

**Comment by elupus** [comment]
Thanks. Looks like I made an error. Will fix.

**Comment by elupus** [comment]
Should be fixed now

**Comment by bohtho** [comment]
Can confirm. Thanks!
