### ISSUE TITLE
Repeated errors in the log

### ISSUE THREAD

**Issue by stphndrnd** [elupus/hass_nibe#31]
Hi,

While browsing logs I just noticed that I get the following message repeatedly for many sensors in my system.

Does anyone else have it? If so, how did you solve it and make it disapear? The message does not make much sense to me.

Thanks!

```
2019-03-31 05:12:24 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.nibe_XXXXX_YYYYY fails
  File "/config/custom_components/nibe/entity.py", line 250, in async_update
  File "/config/custom_components/nibe/entity.py", line 149, in async_update
  File "/config/custom_components/nibe/entity.py", line 144, in get
  File "/config/deps/lib/python3.7/site-packages/nibeuplink/__init__.py", line 453, in get_parameter
  File "/config/deps/lib/python3.7/site-packages/nibeuplink/__init__.py", line 424, in get_parameter_raw
  File "/config/deps/lib/python3.7/site-packages/nibeuplink/__init__.py", line 367, in _request
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.nibeuplink.com:443 ssl:None [Try again]
```

**Comment by elupus** [comment]
Looks like your internet connection is flaky.

**Comment by stphndrnd** [comment]
Could also be that the API has a rate limit. If so, then other people would see the same thing in the logs.

**Comment by elupus** [comment]
Nope. That is a connection error. Rate limit would be an error code.

**Comment by stphndrnd** [comment]
Ok. will investigate the firewalls. maybe it is there since my connection is rather stable. Any ports or pinpointers I can use?

**Comment by elupus** [comment]
Could be dns.

**Comment by elupus** [comment]
Do you have ipv6?

**Comment by stphndrnd** [comment]
no

**Comment by stphndrnd** [comment]
So I checked all firewalls, adblocker at DNS level, etc. opened everything that can be related to a api.nibeuplink.com and still get messages such as

`Update of sensor.nibe_XXXXX_YYYYY is taking over 10 seconds`

Those are warning appearing in the info tab, looking at the error log. The other errors have disappeared.

Any ideas?

**Comment by imist** [comment]
I get a lot of these too and am also interested in why.
Is it the Nibe uplink api backend that is slow to respond perhaps?

**Comment by bohtho** [comment]
Isn't this when you have activated all available sensors in the configuration, and because Uplink only allows retrieving 15 parameters at a time and has a rate-limit of 5 seconds, Homeassistant warns of slow updating for the parameters that are in queue ?

**Comment by stphndrnd** [comment]
@bohtho - yes, that makes very much sense. Is there a way in this plugin to take the rate limit into account?

**Comment by elupus** [comment]
It is rate limiting, that is why you get those. The problem is that Hass polls every sensor every intervall instead of spreading it out evenly. It's technically a non issue. But yes annoying.

**Comment by stphndrnd** [comment]
Well it actually just became an issue. See what i get in the logs below

```
nibeuplink.exceptions.UplinkResponseException: RATE_LIMIT: Rate limit. Too many requests.
{'httpStatusCode': 400, 'errorCode': 28, 'timestamp': '2019-04-16T07:08:52.1783333Z', 'details': ['You have exceeded the API request rate limit and have been blocked temporarily.'], 'data': None}
```

How do we escalate this the Hassio team if the problem is that their end?

**Comment by elupus** [comment]
It's not their issue. Very odd.

**Comment by elupus** [comment]
We are limiting to every 4 seconds. But maybe they count 4 seconds from when last request completed. That would cause us to overstep.

**Comment by imist** [comment]
FWIW: I hit this rate limit frequently too resulting in sensors showing up as unavailable which in turn falsely triggers some of my automations when the become available again.

**Comment by bohtho** [comment]
I also get it from time to time, but I try to "rate limit" my own automations to avoid getting temporarily blocked. Not ideal.

**Comment by elupus** [comment]
I've pushed a new version which increase rate limit to 4.5 seconds and counts time from the finished request instead of as a 4 second running interval. Hopefully solve your RATE_LIMIT errors. It won't remove the warning about taking longer than 10 seconds to update thou.

**Comment by stphndrnd** [comment]
Git pulled. I will report if I see more errors. If within one week nothing is there anymore then I will close this issue.

**Comment by elupus** [comment]
The issue Update of sensor.nibe_XXXXX_YYYYY is taking over 10 seconds is likely now solves.
