### ISSUE TITLE
Error when checking configuration

### ISSUE THREAD

**Issue by a94marbo** [elupus/hass_nibe#32]
Hi, I get this error message when checking the configuration:
"Invalid config for [nibe]: expected int for dictionary value @ data['nibe']['systems'][0]['system']. Got '<my API key>'. (See /config/configuration.yaml, line 335). Please check the docs at https://home-assistant.io/components/nibe/"

my API key is a mix of letter and numbers.
row: 335 is the first line "nibe:"

My config looks like this:
nibe:
    systems:
        - system: <my API key>
          units:
            - unit: 0
          climates: True
          water_heaters: True

**Comment by imist** [comment]
You need to provide your SystemId. It can be found in the url after you’ve logged in to Nibe uplink (xxxxx in the example below)

https://www.nibeuplink.com/System/xxxxx/Status/Overview

**Comment by a94marbo** [comment]
Ok, thanks. I had my API key instead of the system id.

**Comment by lassem** [comment]
The information in the comment from @imist should be included in the README.

**Comment by bohtho** [comment]
There’s a pull request with updated docs.

**Comment by imist** [comment]
Has the doc been published yet? If so, where can I find it?
This component is so powerful but so hard to install, configure and understand.
Take all timeouts due to hitting the rate limit. A best practice guide on how to avoid this would be nice. 🤔

Michael

**Comment by bohtho** [comment]
@elupus has merged in the updated docs. Check the readme.
