### ISSUE TITLE
Water heater modes - Heat pump and high demand - What is that?

### ISSUE THREAD

**Issue by stphndrnd** [elupus/hass_nibe#33]
Hey guys,

When configuring the water heater mode I see all the options I have in my pump (F750) for water heater. However there are 2 modes heat_pump and high_demand. I can't relate those in the parameters in my pump. What are those for?

Thanks!

**Comment by bohtho** [comment]
I think exactly those two are status from the system and not settable for the user. I always thought "heat_pump" was default water heating (if not "eco", "boost", etc.) and that "high_demand" might be normal default when the system needs additional heating too. But it's not clear in the manuals.

**Comment by stphndrnd** [comment]
Would make sense. What do you mean exactly with "when the system needs additional heating too"?

**Comment by bohtho** [comment]
"additional" is the extra electric immersion water heater (if I'm correct).

**Comment by stphndrnd** [comment]
OK. I think I know what you mean but not sure. Anyway I will leave it out as a possible mode but possible to activate from end user. just status.

**Comment by stphndrnd** [comment]
That might explain a few things on my question: https://developers.home-assistant.io/docs/en/entity_water_heater.html#states - However I none of those states in my F750 so I still have a hard time to relate. Is this component fetching the list of available options in the heat pump dynamically or is it a fixed list and then up to each of us to customise it based on what the pump and do or not? Maybe a question for @elupus 

Another question: how can I get the list of options in Swedish i.e. instead of one_time_boost I would like to get "engångshöjning" - Is that possible without writing my own input select and set of automations?

**Comment by elupus** [comment]
At the moment you can not get them in swedish. They are fixed values, so the plug-in need to know them all in advance.

Mapping us as follows currently:
Eco = eco
Heat pump = normal
High Demand = luxury

Then the boost modes.

**Comment by elupus** [comment]
Closing since list is now only boosts modes.
