### ISSUE TITLE
Water heater throwing errors - Why?

### ISSUE THREAD

**Issue by stphndrnd** [elupus/hass_nibe#35]
Hi,

Trying to get my head around how the water heater of this custom component is working. Can someone clarify?

1. When I update the water settings in my pump it does not update anything in the water_heater component?
2. It always starts as "eco" regardless of the current mode of the heat pump settings
3. When calling the service to set the correct settings I get errors. See below

```
Call
data:
  entity_id: water_heater.nibe_<id>_40014
  operation_mode: eco
service: water_heater.set_operation_mode
```

I get this

```
2019-04-18 15:32:51 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1843666192] FORMAT_ERROR: Input format error.
{'httpStatusCode': 400, 'errorCode': 1, 'timestamp': '2019-04-18T13:32:51.5655915Z', 'details': ['Error 14:  47041'], 'data': None}
aiohttp.client_exceptions.ClientResponseError: 400, message=''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 314, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 328, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/config/custom_components/nibe/water_heater.py", line 243, in async_set_operation_mode
    HA_STATE_TO_NIBE[operation_mode])
  File "/config/deps/lib/python3.7/site-packages/nibeuplink/__init__.py", line 490, in put_parameter
    headers = headers,
  File "/config/deps/lib/python3.7/site-packages/nibeuplink/__init__.py", line 398, in _request
    await raise_for_status(response)
  File "/config/deps/lib/python3.7/site-packages/nibeuplink/__init__.py", line 189, in raise_for_status
    data) from e
nibeuplink.exceptions.UplinkResponseException: FORMAT_ERROR: Input format error.
{'httpStatusCode': 400, 'errorCode': 1, 'timestamp': '2019-04-18T13:32:51.5655915Z', 'details': ['Error 14:  47041'], 'data': None}
```

Is this component to monitor if the heat pump is producing warm water or not? What's the intention?

Thanks!

**Comment by elupus** [comment]
Yes it is to monitor when it is producing water and setting boost mode. 

But seems its not accepting the selected boost mode. 

Updates to modes take several minutes, when done from the pump to reflect in Hass.

It is using the parameter: 47041 and hot_water_boost to select. I think only the boost modes are allowed to be selected from uplink.

But please add those two parameter to your config as standard parameter and check this values.

**Comment by stphndrnd** [comment]
Hi,

> It is using the parameter: 47041 and hot_water_boost to select. I think only the boost modes are allowed to be selected from uplink.

I have tried that, waited 10min. Not working.

> But please add those two parameter to your config as standard parameter and check this values.

What do you mean by that?

Thanks

**Comment by elupus** [comment]
Look at the sensors section in config. You can add any parameter there to get a sensor for it.

**Comment by stphndrnd** [comment]
I'll try that. But that still doesn't not explain the errors when I use the function water_heater.set_operation_mode (see above in the thread). every time I select this function in HA the guy hangs and when I script it in automation it throws the error. I used debug logs and that is all there is in there on this.

**Comment by elupus** [comment]
It does not explain it, but it can help me debug it.

**Comment by stphndrnd** [comment]
Hey,

Reading this thread again I now get it.

Some time ago I did have a chat with Nibe support around the list of params that writeable. Turns out you can read a lot but not write a lot. Basically the only writeable params are here: https://api.nibeuplink.com/docs/v1/Parameters

That's it. 47041 is not in the list. If the object water heater is trying to do a PUT on the value then it will throw an error. Only the hot_water_boost will be accepted.

When I read the 47041, it gives me the value "economy" and not "eco", could be another thing but I don't believe in it.

What happens if you try to run the API calls you do in your Python code in POSTMAN? Works or not?

Thanks!

**Comment by elupus** [comment]
I dont have premium so can't test. It should write hot_water_boost if you select any of the boost modes.

**Comment by elupus** [comment]
I think i found the issue with boost modes. I was setting a string instead of an int. i think that causes it to interpret it in given language.

I've also dropped the eco/luxuary stuff from water heaters. those can't be set anyways.

**Comment by stphndrnd** [comment]
Hi,

Just tried the new code. It works but it is confusing. The auto mode doesn't do anything. Any boost mode just triggers the one-time boost for 3hrs. That's it. Reading the current status of the various boosts form the heat pump when changed in there doesn't work (I think it is not possible). To me it is better to just leave the option of monitoring param 47041 to know if warm water is produced or not and then just use the "hot_water_boost" switch.

**Comment by elupus** [comment]
Well auto is normal mode. Maybe should have just called it normal. 

Reading the boosts does work. If you select 6 hours it will eventually show 6 hours in HA. But it takes several minutes.

The water heater will be ON when producing hot water and OFF otherwise.

**Comment by stphndrnd** [comment]
> Reading the boosts does work. If you select 6 hours it will eventually show 6 hours in HA. But it takes several minutes.
You mean selecting in the heat pump will provide a read in HA? Because setting any value in the list will just set the one-time in the heat-pump

**Comment by elupus** [comment]
Yes setting it on the pump, then you should get that shown in HA.

**Comment by elupus** [comment]
I'm closing this since original issue is no longer valid. Open a new issue if there is still something amiss.
