### ISSUE TITLE
Hass.io 0.94.0

### ISSUE THREAD

**Issue by nolenjohan** [elupus/hass_nibe#41]
I get this error message in the Nibe panel:

![screenshot 834](https://user-images.githubusercontent.com/34334118/59016789-5bbf6600-8842-11e9-9b72-4bc21a7f0c5b.jpg)

Checking States:

![screenshot 835](https://user-images.githubusercontent.com/34334118/59016802-61b54700-8842-11e9-83fc-7d6d3e894cd1.jpg)

Is there a mis-match of entity name?

**Comment by elupus** [comment]
Are you running Lovelace? Then you must update your config. The water heater entity have changed name. (The sensor.xxxx entity is different). It you don't have water heaters enabled in config.

**Comment by nolenjohan** [comment]
Yes, Lovelace since a while back. What in configuration.yaml needs to be updated?

**Comment by elupus** [comment]
Have you edited Lovelace or is it still Auto generated?

**Comment by nolenjohan** [comment]
Auto generated in Lovelace

**Comment by nolenjohan** [comment]
OK! Got it! Now I manually edited Lovelace and changed to the new entity name.
Thanks!

**Comment by elupus** [comment]
Are you sure? Do you get a warning when you press the edit button?

**Comment by nolenjohan** [comment]
Hmmm... my memory, I was sure that I only edited States UI manually, in groups.yaml, not Lovelace. But now I'm getting unsure... :-)

**Comment by nolenjohan** [comment]
I might have added:

show_header_toggle: false

to all cards.

**Comment by elupus** [comment]
Also look in your entities list for the water_heater.* entity. There should be one, but it can be named different.

**Comment by elupus** [comment]
Right, if you edited Lovelace it doesn't auto generated anymore. So you need to adjust the group, and fix the reference to the water heater entity.

**Comment by bohtho** [comment]
What's the new correct entity for the water heater though ? I also had auto-generated lovelace, but still got this same error on update. As well as the following errors:
<img width="1148" alt="Error screenshot" src="https://user-images.githubusercontent.com/13752/59158089-6897c000-8ab5-11e9-92aa-4bb5ec99eb78.png">

**Comment by elupus** [comment]
Did you look for it in the entities list?

**Comment by bohtho** [comment]
Can't seem to find them in the entities. But I also get this error since updating: 

> The following components and platforms could not be set up: - nibe.climate - nibe.water_heater - nibe.fan Please check your config.

**Comment by elupus** [comment]
Then you have an old version of the nibeuplink library.

**Comment by bohtho** [comment]
Do I have to upgrade that separately now?! I git pulled your custom component as usual and restarted home assistant.

**Comment by elupus** [comment]
It should have updated automatically. Hass.io always seem to behave odd. Nothing earlier in the log.

**Comment by bohtho** [comment]
Oh, sorry, no, I'm not on Hass.io. Normal Home Assistant on Raspbian.

**Comment by elupus** [comment]
Okey. So can you enter the venv that home assistant is running in and do a:
`pip uninstall nibeuplink`

It should reinstall on next home assistant restart.

**Comment by bohtho** [comment]
Sorry, bu I don't know what a `venv` is. Currently when I run the command I get:

> Cannot uninstall requirement nibeuplink, not installed

**Comment by elupus** [comment]
That is probably why it's not working properly then. Which install method did you follow?

**Comment by bohtho** [comment]
Installed via DietPi’s software installation UI. They usually follow official recommendations. Plus hass_nibe has worked flawlessly up until latest version.

**Comment by elupus** [comment]
Okey, you need to figure out how to enter the venv it runs home assistant in. Then uninstall nibeuplink.
 I suspect it's in /home/homeassistant/.pyenv/versions/3.6.3/envs/homeassistant-3.6.3

**Comment by bohtho** [comment]
Found out how to enter venv and uninstalled nibeuplink, but then every sensor failed in home assistant on restart. So had to manually install nibeuplink too then it worked again! (Except sensor 43424, 43420 and 43416 which I don't remember if I experimented with and added myself in the config, or if you have changed them...)

**Comment by elupus** [comment]
Could you give me a log of when you started with nibeuplink uninstalled? I want to know why it didn't install it automatically.
