### ISSUE TITLE
Recent change in home-assistant breaks your code?

### ISSUE THREAD

**Issue by philippkoelmel** [elupus/hass_nibe#43]
Hey,

thank you for the great work! A recent change in home-assistant seems to break your code:
https://github.com/home-assistant/home-assistant/commit/319ac23736058fe0a5c4b66a2758bbd3e200d0aa

I removed /homeassistant/config_entries.py:556 to 563, restart the software and it worked:
https://github.com/home-assistant/home-assistant/commit/319ac23736058fe0a5c4b66a2758bbd3e200d0aa#diff-9e423b96591ab40119af2f0c56ff55cdR556

Not a reliable solution of course. Any recommendation?

Regards!

**Comment by elupus** [comment]
Sadly no reliable solution yet. I will try to get a fix into homeassistant. It need to support flows on custom component.

**Comment by philippkoelmel** [comment]
Happy to help, please let me know if I can contribute

**Comment by elupus** [comment]
Awaiting: https://github.com/home-assistant/home-assistant/pull/24946

**Comment by elupus** [comment]
With current beta of home assistant as well as dev branch. This is again working. Will close issue once next release is out and this is merged to master.

**Comment by elupus** [comment]
Now working
