### ISSUE TITLE
Missing sensor and others are unavailable

### ISSUE THREAD

**Issue by nolenjohan** [elupus/hass_nibe#44]
As per below pic, one sensor is suddenly not present and some others (underlined with red) are now unavailable, is this related to current version of Hass.io? I'm using 0.97.2
![screenshot 858](https://user-images.githubusercontent.com/34334118/63020881-8ca1c400-be9f-11e9-97ff-60758fc64469.jpg)

**Comment by elupus** [comment]
My guess would be a change by nibe. They define what goes into which section. With Lovelace it is a bit tricky since the group's won't update themselves. So you may have new sensors to replace the ones that are unavailable or missing.

**Comment by elupus** [comment]
Hmm. All sensors are unavailable for me right now.

**Comment by elupus** [comment]
"Important!
We're performing some maintenance at the moment which might temporarily affect the availability and functionality of the service. This does not affect the system's functionality with regards to heating and cooling. Sorry for the inconvenience, we'll be back online shortly. "

**Comment by nolenjohan** [comment]
OK, but one of my sensors have disappeared or changed name, checked for similar names but could not find...

**Comment by nolenjohan** [comment]
Never mind, after a restart the sensor is back again.
