### ISSUE TITLE
State of ventilation_boost

### ISSUE THREAD

**Issue by patsch9** [elupus/hass_nibe#45]
When you add the ventilation_boost switch, the "on" state of the switch can not be displayed. 
The "off" value from ventilation boost returns 0 and the "on" value returns 4. The switch only reacts to 0 for off and 1 for on.

**Comment by elupus** [comment]
Add fans instead

**Comment by pseckd** [comment]
> Add fans instead

how do I do that

**Comment by elupus** [comment]
# Optional fan entities
          fans: True


Den mån 19 aug. 2019 12:46pseckd <notifications@github.com> skrev:

**Comment by pseckd** [comment]
fans is already set to true

**Comment by elupus** [comment]
And do you not have a fan entity?

**Comment by pseckd** [comment]
i only can fix this yet by using a template switch with following template_value: '{% if is_state_attr("switch.nibe_XXXXX_ventilation_boost", "display_value", "speed 4 (100%)") %} on{% else %} off {% endif %}'

**Comment by elupus** [comment]
could you give me a debug log. Add this to your configuration and restart.

logger:
    default: info
    logs:
        custom_components.nibe: debug
        custom_components.nibe.entity: debug
        custom_components.climate.nibe: debug
        custom_components.sensor.nibe: debug
        custom_components.water_heater.nibe: debug
        nibeuplink: debug

**Comment by elupus** [comment]
No response from user.
