### ISSUE TITLE
Integrations not working

### ISSUE THREAD

**Issue by nolenjohan** [elupus/hass_nibe#47]
I have a new installation of Hass.io 0.99 and can't add Nibe Uplink, when clicking "Nibe Uplink" in Integrations page (plus sign and choose from list), nothing happens, it jumps directly back to the list of availible integrations. Have rebooted several times and tried again. No luck. 

Any ideas?

**Comment by elupus** [comment]
Hmm. No, Will have to check. But check log, there might be some clue. You have current version of the custom component?

**Comment by elupus** [comment]
This could be: https://github.com/home-assistant/home-assistant/issues/26720

So first await patch release of HA.

**Comment by nolenjohan** [comment]
Ok, thanks!
Checked my minimal log (Critical) and can see this:

Log Details (WARNING)
Thu Sep 19 2019 16:39:05 GMT+0200 (centraleuropeisk sommartid)
You are using a custom integration for nibe which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

Seems strange since I did not succeed to integrate it, is it because I have the files in the directory? Or can there be remains from previous backed up files (added to new installation) that fool the system? I removed "Nibe Uplink" from previous installation before copying the files in "Config" share as a backup to be used in new installation.

**Comment by elupus** [comment]
So by that you mean you are not using latest version?

**Comment by nolenjohan** [comment]
I'm using the latest version of Hass.io and of your integration (the files downloaded from this page). I regularly take backups of all content in "config" share. Two weeks ago I removed "Nibe Uplink" by delete the integration from within the web-GUI, I also deleted any associated Lovelace lines (since I had made modifications they did not disappear when deleting the integration.

Yesterday my SD-card died... used a new SD-card and "etched" latest Hass.io version to it, after start and being ready I had HA at version 0.99.0. Copied all content of the backup ("config" share) to the new installation, everything back as before.

Tried to add "Nibe Uplink" again, get the issues as described in the start of this thread.

**Comment by elupus** [comment]
Right. So then let's start by waiting for 0.99.1 release. Since bug mentioned above will likely block adding the integration.

If you don't want to wait install Hass with 0.98 and add integration there, then upgrade to 0.99.

**Comment by elupus** [comment]
Ps. Check that you backups contain the hidden ".storage" folder. If those where there you should not have needed to add the integration again.

**Comment by nolenjohan** [comment]
Yes, backups contains the hidden ".storage" folder, though I deleted the integration before I took the backup (I only save one version of backup). All other integrations did appear after copying the backup to the "config" share, like "Philips Hue", "Telldus Live", "UNIFI Controller" etc. without the need to redo the integrations.

**Comment by nolenjohan** [comment]
Upgraded to 0.99.2 and could add the "Nibe Uplink" integration with successful result, but, there are no sensors, completely empty...
![screenshot 864](https://user-images.githubusercontent.com/34334118/65307011-1b80bb00-db87-11e9-8d9b-03a1e4b70838.jpg)

I also receive this error message:
![screenshot 865](https://user-images.githubusercontent.com/34334118/65307058-36ebc600-db87-11e9-8abd-d3121a7feadb.jpg)

My config in configuration.yaml:
nibe:
    systems:
        - system: 12345 (masked with another number)
          units:
            - unit: 0
              categories: True
              statuses: True
          sensors:
          switches:
            - hot_water_boost
          climates: True
          water_heaters: True

**Comment by elupus** [comment]
Check log

**Comment by nolenjohan** [comment]
![screenshot 866](https://user-images.githubusercontent.com/34334118/65308164-c1352980-db89-11e9-85af-a40088b0699c.jpg)

**Comment by elupus** [comment]
I need the details.

**Comment by nolenjohan** [comment]
I hope this is sufficient:

2019-09-20 09:39:30 INFO (SyncWorker_15) [homeassistant.util.package] Attempting install of nibeuplink==0.9.1
2019-09-20 09:40:17 INFO (MainThread) [homeassistant.setup] Setting up nibe
2019-09-20 09:40:17 ERROR (MainThread) [homeassistant.setup] Error during setup of component nibe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/nibe/__init__.py", line 165, in async_setup
    await async_register_services(hass)
  File "/config/custom_components/nibe/services.py", line 58, in async_register_services
    from nibeuplink import SMARTHOME_MODES, SetThermostatModel
ImportError: cannot import name 'SMARTHOME_MODES' from 'nibeuplink' (/config/deps/lib/python3.7/site-packages/nibeuplink/__init__.py)
2019-09-20 09:40:17 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Invalid config, message=The following components and platforms could not be set up:

 - [nibe](https://home-assistant.io/components/nibe/)

Please check your config., notification_id=invalid_config>

2019-09-20 09:40:18 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=None, new_state=<state persistent_notification.invalid_config=notifying; title=Invalid config, message=The following components and platforms could not be set up:

 - [nibe](https://home-assistant.io/components/nibe/)

'Authorization was successfull! Entities will now be added.', 'component.nibe.config.error.code': "Couldn't get an access token from code. Further information may be in home assitant log", 'component.nibe.config.abort.already_configured': 'Uplink is already configured', 'component.logi_circle.config.abort.already_setup': 'You can only configure a single Logi Circle account.', 'component.logi_circle.config.abort.external_error': 'Exception occurred from another flow.', 'component.logi_circle.config.abort.external_setup': 'Logi Circle successfully configured from another flow.',

**Comment by elupus** [comment]
Looks weird. It sort of looks like you have an old version of nibeuplink in your config folder at /config/deps/lib/python3.7/site-packages/nibeuplink

Could you try and delete that folder and restart?

**Comment by nolenjohan** [comment]
Delete both folders?
![screenshot 867](https://user-images.githubusercontent.com/34334118/65324146-a7a4d980-dbab-11e9-9f52-28f4703a6745.jpg)

**Comment by nolenjohan** [comment]
Deleted both folders and restarted HA, no errors and now I can find many sensors/devices in "Developer Tools" -> "States", but they are not showing up in the web GUI

**Comment by elupus** [comment]
Lovelace is not auto generated. You need to create that manually.

**Comment by nolenjohan** [comment]
Aha, ok! Thanks!

**Comment by toni1703** [comment]
Hello
My nibe is setup and running...My problem is that if my electrical power is off , when it comes back on my raspberry pi starts faster then the nibe system and the nibe integration in HA does not load (saying in HA unavailable). I would much apreciate a solution to this problem. Thanks in advance. 


![image](https://user-images.githubusercontent.com/23199856/104649624-ad3a0300-56bd-11eb-802a-41287b54611d.png)
