### ISSUE TITLE
Change root folder of repository to "custom_components"

### ISSUE THREAD

**Issue by bohtho** [elupus/hass_nibe#48]
Would you consider changing the root folder for the repository to "custom_components" (like most other Hass custom components) so that it can be installed and updated through HACS (Custom repository) ?

**Comment by elupus** [comment]
Nope. But HACS support my layout now.

**Comment by bohtho** [comment]
Oh really? I tried to add the repository to custom repositories in Hacs but it failed while searching for the custom_components directory.

**Comment by elupus** [comment]
I need to add a description file.

**Comment by bohtho** [comment]
Ok. That would be great!
