### ISSUE TITLE
When restarting, thermostats are set to Off

### ISSUE THREAD

**Issue by matlimatli** [elupus/hass_nibe#51]
Every time I restart my Home Assistant, all the defined thermostats are set to "Off" mode, meaning they will not report set or current temperatures to Nibe Uplink. 

I would prefer them to enter "Heat/Cool" mode, either by default or by a setting.

**Comment by elupus** [comment]
Okey. Weird just checked the code. They should restore their previous state.

**Comment by elupus** [comment]
Do you have recorder component active in HA? Does it include these entities?

**Comment by matlimatli** [comment]
No, the recorder is not active at all.

**Comment by elupus** [comment]
Then that is why. We restore state based on data in recorder.

**Comment by matlimatli** [comment]
Aha. Makes sense, I guess. Which entities should be enabled in recorder for optimal functionality?

**Comment by elupus** [comment]
Only the climate entity in question needs this. Nothing else restore state if i remember correctly.

**Comment by matlimatli** [comment]
I enabled recorder (and just excluded some specific and unrelated high-volume entities), history and logbook. The set temperature seems to be recalled, but the operation mode is still "Off" after a restart.

**Comment by elupus** [comment]
Think i got this fixed. Update to latest version and re-test. Reopen if you still have issue.

**Comment by matlimatli** [comment]
Works like a charm. Thanks!
