### ISSUE TITLE
Authorize link is missing

### ISSUE THREAD

**Issue by nolenjohan** [elupus/hass_nibe#52]
I had to re-install my Hass.io, when trying to add integration "Nibe Uplink" and after having entered "Identifier" and "Secret" I end up with this dialogue, not sure what to do?
I have tried open another tab in browser and surfing to https://api.nibeuplink.com/ but no success. 

![screenshot 879](https://user-images.githubusercontent.com/34334118/68130621-f4eec780-ff1b-11e9-9cc5-e9ed4b1c52e3.jpg)

In the pic in \config\custom_components\nibe\docs\ I can see that the dialogue should contain a "Authorize" link:

![nibe_authorize](https://user-images.githubusercontent.com/34334118/68130629-fc15d580-ff1b-11e9-84a9-53022005bf9d.png)

**Comment by elupus** [comment]
Have you grabbed latest nibe uplink component?

**Comment by nolenjohan** [comment]
Yes, just an hour ago.

**Comment by nolenjohan** [comment]
I found this link:

https://api.nibeuplink.com/oauth/authorize?response_type=code&client_id=[CLIENT_ID]&scope=[SCOPES]&redirect_uri=[REDIRECT_URI]&state=[STATE]

Can't figure out what to replace [STATE] with? The other I have replaced with my data.

**Comment by elupus** [comment]
You can't . It's generated by the addon

**Comment by nolenjohan** [comment]
So why is the link missing? Error on my Hass.io or in the integration?

**Comment by elupus** [comment]
The image you mentioned is from an old version of the plug-in. Maybe you
still have a link to the old dev branch?

Please remove and reclone.

Den mån 4 nov. 2019 16:19Johan Nolén <notifications@github.com> skrev:

**Comment by nolenjohan** [comment]
That did the trick!

But, even though integration successful, I don't get any devices within that integration:

![screenshot 880](https://user-images.githubusercontent.com/34334118/68137143-c1fe0100-ff26-11e9-8470-bbfa0402e538.jpg)

I also get this notification:

![screenshot 881](https://user-images.githubusercontent.com/34334118/68137281-0093bb80-ff27-11e9-8d59-e1346cea2579.jpg)

**Comment by elupus** [comment]
Check log

**Comment by nolenjohan** [comment]
Found the issue, deleted old files within:
\config\deps\lib\python3.7\site-packages\

Restarted and now it works perfect!
