### ISSUE TITLE
[question] Fetching parameters and controlling heatpump via modbus

### ISSUE THREAD

**Issue by yozik04** [elupus/hass_nibe#54]
I am trying to get rid of my openhab2 system and use hass as my main system. Openhab has a binding [Nibe Heatpump Binding](https://www.openhab.org/addons/bindings/nibeheatpump/) which I am currently using. It uses Modbus connection and an Arduino with Ethernet Shield. All this is way more stable than Nibe Uplink. I am using it for a half a year now. Controlling heating/cooling temperature offsets, water comfort modes, reading all parameters that I need, enabling/disabling heating and cooling for FREE.

Does it make sense to try to change current project to support second communication method or it is better to create a separate project? I am ready to contribute.

**Comment by runevad** [comment]
I used [this](http://husdata.se/produkter.asp?prodid=30) (husdata.se) before and it was excellent, I still have the card lying around here somewhere but not plugged in anymore. It also uses MODBUS and was rock solid. It fetched almost all the parameters I wanted (at the time I didn't get the parameters for electricity price and a few others, not sure these can be reached through MODBUS or not) and I used it in combination with MQTT to sent the parameters to Home Assistant. 

I might be interested in using MODBUS again just to have a fail safe and be a little less dependent on the nibe cloud.

**Comment by elupus** [comment]
You guys should have a look at: https://github.com/bebben88/NibePi Seems like neat solution. No integration for home assistant yet. Mostly standalone. But post a note on his issue page. Link back here :)

**Comment by yozik04** [comment]
I have started writing a python library to work with `nibegw`, but it is stuck now due to lack of free time. Probably when COVID will end I will have time again to continue.

**Comment by DenisMir** [comment]
@yozik04 Did you went on with writing this python library?

**Comment by yozik04** [comment]
No. I did not. Feel free to do it :)

**Comment by elupus** [comment]
I might if i end up building a nibepi hardware. But its just a might :)

**Comment by yozik04** [comment]
I would not go via RPI hardware. Arduino with a netmodule or ESP module would be much better so it would handle sending acks back to Nibe by itself. It can be powered via Nibe heatpump. On the other side would be RPI or any other thing that would communicate with Arduino/ESP to query data it is interested in. This way if you reboot RPI your heatpump will not go into alarm state.

**Comment by elupus** [comment]
The nibepi hardware is powered by the pump. But sure it's rather pointless to have all that power. Would be nicer to just have a nibe to tcp modbus gateway as an esphome hardware. Then it could act identically to the new S series pumps.

**Comment by yozik04** [comment]
New S series pumps have TCP Modbus exposed?

**Comment by elupus** [comment]
> New S series pumps have TCP Modbus exposed?

Yup

**Comment by yozik04** [comment]
So this is the way to go for sure =)

**Comment by DenisMir** [comment]
I have gone the easy way now (at least for me since I am no Python guy at all). I'm running a Prodino MKR Zero Ethernet with NibeGW. (powered by the F1255) The client side is NibePI (which has a NibeGW client) and is running inside a simple homeassistant addon. It is collecting the NibeGWs UDP data and publishes it via MQTT as well as it allows to write data via MQTT the other way round.

**Comment by yozik04** [comment]
@DenisMir I have pushed a Nibe modbus library today. To work with NibeGW developed for Openhab.
https://github.com/yozik04/nibe
I think it has all required parts to get started. It should be plug and play replacement for Openhab's nibeheatpump integration.
I will start implementing MQTT version of integration next week.
