### ISSUE TITLE
Tried to install via HACS but cant add repo...

### ISSUE THREAD

**Issue by Snille** [elupus/hass_nibe#55]
Hi, I'm trying to uniform all my "custom_components" thereby installing everything form HACS.
However, I'm not able to add "this" (https://github.com/elupus/hass_nibe.git) repository to HACS.
I tried adding it via "settings" and then "costume repositories", selected the "integration" option.

Got this in response: 
![image](https://user-images.githubusercontent.com/1011699/71257543-3ef90480-2334-11ea-8b60-9d369b0aa17c.png)

Am I doing it wrong?

**Comment by runevad** [comment]
Only add the link to the repository, not the .git
https://github.com/elupus/hass_nibe

**Comment by Snille** [comment]
Sorry, I should have tested that. :) 
Thank you!
