### ISSUE TITLE
Filter Alarm in Hassio?

### ISSUE THREAD

**Issue by f00dagi** [elupus/hass_nibe#60]
Thanks for a great integration into Home Assistant! It was easy to get started.

My Nibe F750 regularly throws a filter alarm when it is time to clean the filter. Can this in anyway be detected through your integration?

This is not a bug, rather a feature request or simply a question what is doable with your integration?

Thanks!

![6CBDB386-7790-4621-A6DA-10759856C640](https://user-images.githubusercontent.com/56124786/73693397-73533500-46d6-11ea-90e7-f3d91baace2a.png)

**Comment by elupus** [comment]
You don't get a notification when it occurs? We do signal some alarms that way (or intend to). Nibe have hidden some notification behind special deals. So it might not be availability from the API.
Check log for error when you have such a note.

**Comment by f00dagi** [comment]
Thanks for your reply. What ID should I use to get the filter alarm notification? 45001, 47275?

What value should I be looking for to identify the alarm, I cannot find any documentation?

Thanks!

-Daniel

On 3 Feb 2020, at 22:48, Joakim Plate <notifications@github.com> wrote:

﻿

You don't get a notification when it occurs? We do signal some alarms that way (or intend to). Nibe have hidden some notification behind special deals. So it might not be availability from the API.
Check log for error when you have such a note.

**Comment by elupus** [comment]
It's not a parameter. Separate service: https://api.nibeuplink.com/docs/v1/Api/GET-api-v1-systems-systemId-notifications_type_active_page_itemsPerPage

**Comment by elupus** [comment]
In Hass I try to expose that as notifications.

**Comment by f00dagi** [comment]
Thanks, I have read the documentation via the link but honestly I have no idea where to start to get this working in Home Assistant. Reading IDs like temperatures and current work just fine through the integration but read alarms through notifications seem very different.

Do you have (or can point to) some example code it would be very much appreciated.

**Comment by elupus** [comment]
First of all. It theoretically should already show up as a notification in Hass. But as I said I've not got any verification on that.

If you want to debug it, you would have to look in this components code. It uses the nibeuplink python project to make API calls to the nibe servers on the above endpoint.

It's not possible from Hass only.

**Comment by f00dagi** [comment]
It might be that I am too much of a newbie to understand exactly what you are describing and I understand that you dont have time to educate your users but...

In this context, what do you mean by "show up as a notification in hass"? Do you mean as an entity? Is there a service in hass.io that I should use? How do I detect this notification?

**Comment by elupus** [comment]
Notifications in Hass are stuff like errors and new discovered devices.. I have no idea of you can act on them.

**Comment by rangulvers** [comment]
The notification within the HASS UI works fine as they should. But it would be nice to have the notification as a separate entity to be able to include it in the automation. E.g It is not working with the mobile notification since the Hass UI notifications are not pushed to the app. 

somthing like 

Sensor : Nibe Notification
-Entitiy : Notification Available
--Parameter : ON/OFF
-Entity : Notification 
--Parameter : Notifiaction Test
