### ISSUE TITLE
Install via HACS overwrites all custom_components

### ISSUE THREAD

**Issue by nickcj931** [elupus/hass_nibe#61]
Just re-installing my NIBE integration using HACS as per guide and it completely overwrites the custom_components folder when you uninstall the ingetration. Meaining that cusom_components folder is no more with all other components deleted in the process.

Not sure if that is expected outcome? I imagine it should only remove the **nibe** directory?

**Comment by elupus** [comment]
This would be a hacs bug. I'll see if I can ping the developer.

**Comment by ludeeus** [comment]
Fixed with https://github.com/hacs/integration/releases/tag/0.22.2
