### ISSUE TITLE
Heat Meter

### ISSUE THREAD

**Issue by nolenjohan** [elupus/hass_nibe#63]
After upgrading tp 0.107 (I think at least) some sensors become unavailable, see pic below, a known issue? Same on my three different Hass.io installations.

![screenshot 939](https://user-images.githubusercontent.com/34334118/77161477-0b03bb80-6aaa-11ea-8922-1e2608244b69.jpg)

**Comment by elupus** [comment]
Yes. Just update the integration

**Comment by nolenjohan** [comment]
Already done, date on files are March 15.
Checking this area, anything that needs to be cleared/deleted here?
![screenshot 940](https://user-images.githubusercontent.com/34334118/77161926-11defe00-6aab-11ea-8249-f3b7a905eea4.jpg)

**Comment by elupus** [comment]
Nopo. Check your log

**Comment by nolenjohan** [comment]
I searched for one of the sensors that is unavailable, found only the below:

2020-03-20 13:11:34 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.nibe_45666_40072, old_state=None, new_state=<state sensor.nibe_45666_40072=unavailable; restored=True, supported_features=0, unit_of_measurement=l/m, friendly_name=flow @ 2020-03-20T13:11:34.927437+01:00>>

@ 2020-03-20T13:11:34.923442+01:00>, <state sensor.nibe_45666_40072=unavailable; restored=True, supported_features=0, unit_of_measurement=l/m, friendly_name=flow

**Comment by nolenjohan** [comment]
It come to my mind that earlier this week I upgraded the SW on my Nibe system, potential cause?

Now running: 9240R2

**Comment by elupus** [comment]
I'm looking for errors in the log. Not related to sensors.

**Comment by pappirauk** [comment]
Hello,
I'm having the same problem. This error is in my log:
```
2020-03-27 08:55:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
aiohttp.client_exceptions.ClientResponseError: 403, message='', url='https://api.nibeuplink.com/api/v1/systems/XXXX/smarthome/thermostats
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/nibe/climate.py", line 697, in _async_publish
    await self._uplink.post_smarthome_thermostats(self._system_id, data)
  File "/usr/local/lib/python3.7/site-packages/nibeuplink/uplink.py", line 477, in post_smarthome_thermostats
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/nibeuplink/uplink.py", line 238, in post
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/nibeuplink/uplink.py", line 255, in _request
    await raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/nibeuplink/uplink.py", line 43, in raise_for_status
    data) from e
nibeuplink.exceptions.UplinkResponseException: OAUTH_INVALID_SCOPE: OAuth, insufficient scopes for resource.
{'httpStatusCode': 403, 'errorCode': 20, 'timestamp': '2020-03-27T07:55:36.1546591Z', 'details': ['The request is missing a required scope (Required scopes: WRITESYSTEM)'], 'data': None}
```

**Comment by elupus** [comment]
Error above is from your custom thermostats since you didn't request write access when you added the integration
 Not the same thing.

**Comment by pappirauk** [comment]
Ok. Thank you for your quick response.

**Comment by nolenjohan** [comment]
On one of my three Hassio instances, I removed the Integration to Nibe, restarted Hassio, added the integration again, and now I can see that those sensors are totally missing, all the remaining sensors are back as normal:

![screenshot 941](https://user-images.githubusercontent.com/34334118/77739739-5241fd00-7012-11ea-81f8-1c3416640398.jpg)

**Comment by elupus** [comment]
If it's just the heatmeater, then perhaps you updated your firmware. I think nibe invalidly added those. My pump has no flow meter, but those wrongly was added some update ago.

**Comment by nolenjohan** [comment]
Aha, yes, I updated the firmware a week or two ago.
So you're saying that those sensors should not be there, they were added by accident by NIBE and now in the latest firmware upgrade they are removed again?

**Comment by elupus** [comment]
Yes sadly :(. You have to install a real flow meter for those to actually worl
