### ISSUE TITLE
Cannot import name 'UplinkSession' from 'nibeuplink'

### ISSUE THREAD

**Issue by henricm** [elupus/hass_nibe#66]
I've started to get this error and I'm not sure what to do  - it has been working great before.

```
2020-04-02 12:36:49 ERROR (MainThread) [homeassistant.components.hassio] Component error: nibe - cannot import name 'UplinkSession' from 'nibeuplink' (/usr/local/lib/python3.7/site-packages/nibeuplink/__init__.py)
```
I’ve made sure I’ve the latest version of the nibe custom component from master and I’m running HassOS 3.12 and Supervisor version 214.

It seems to have something to do with nibeuplink library that hass_nibe is dependent upon, but I can’t figure out where to look for that library to see if that hasn’t bee upgraded for some reason.

Any ideas how to solve this?

**Comment by elupus** [comment]
My guess is that the nibe uplink component is old. I've seen this occurre before where it is not being upgraded properly. 

You may need to manually remove /usr/local/lib/python3.7/site-packages/nibeuplink on your install. I don't know exactly how you get to that path on hassos though.

**Comment by henricm** [comment]
I managed to access the system by following instructions here: https://developers.home-assistant.io/docs/hassio_debugging
I got ssh access on port 2222 and managed to logon to the docker container bash. Then I was able to locate the /usr/local/lib/python3.7/site-packages/nibeuplink which I removed and restarted homeassistant.
However, now I get another error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/nibe/__init__.py", line 186, in async_setup
    hass.data[DATA_NIBE] = NibeData(config[DOMAIN])
KeyError: 'nibe'
```

**Comment by elupus** [comment]
You need a nibe section in config

**Comment by elupus** [comment]
It can be empty

**Comment by henricm** [comment]
Yay! Of course! :-)
Forgot I had commented out the nibe section, since I didn't got it working. Thanks a lot. Now we're up and running again.
