### ISSUE TITLE
I'm receiving "Invalid Nibe Config"

### ISSUE THREAD

**Issue by iCarl** [elupus/hass_nibe#7]
The system is specified in my configuration.yaml

<img width="488" alt="skarmavbild 2018-06-25 kl 18 08 29" src="https://user-images.githubusercontent.com/4193514/41861910-cc307c5e-78a2-11e8-8330-956f7dd01563.png">

**Comment by elupus** [comment]
So what is your config?!

**Comment by elupus** [comment]
The config has changed since first version of the module. Check the readme.

**Comment by iCarl** [comment]
I've encountered a completely different issue now.

"```
018-06-25 18:18:31 ERROR (MainThread) [homeassistant.config] Invalid config for [nibe]: [writeaccess] is an invalid option for [nibe]. Check: nibe->nibe->systems->0->writeaccess. (See /home/homeassistant/.homeassistant/configuration.yaml, line 73). Please check the docs at https://home-assistant.io/components/nibe/
2018-06-25 18:18:31 ERROR (MainThread) [homeassistant.setup] Setup failed for nibe: Invalid config.
```"


Config:

`nibe:
    client_id: *client id*
    client_secret: *client secret*
    redirect_uri: http://10.0.1.5:8123/api/nibe/auth

    systems:
        - system: 0
          writeaccess: true # set to true to support climate write (needs new tokens)
          categories: # optional list of categories to retrieve, leave empty for all, remove tag for none
            -

          statuses:   # optional list of status screens to retrieve, leave empty for all, remove tag for none
            -

          parameters: # optional list of additional parameters to retrieve, can be done here or on the sensor platform
            - 40033
            - 47398

          climate:
            - platform: nibe
              name: 'Climate System 1'
              system : 0
              current: 40033 # parameter id of current temperature
              target : 47398 # parameter id of target temperature
              adjust : 47011 # parameter id of the parallel adjustment`

**Comment by elupus** [comment]
```
nibe:
    client_id: *client id*
    client_secret: *client secret*
    redirect_uri: http://10.0.1.5:8123/api/nibe/auth
    writeaccess: true # XXXXXXX documentation was wrong, this tag should be under nibe not system.

    systems:
        - system: 51460 # XXXXXXXX must be set to the actual system identifer
          categories: # XXXXXXXX should be empty, not include an empty list value to get all categories
          statuses:   # XXXXXXXX should be empty, not include an empty list value to get all categories

          parameters: # XXXXXXXX only use this if a parameter is not autodeteced by above categories or statuses
            - 40033
            - 47398

# XXXXXXXX climate node should be in the root, not indented into the nibe node.
climate:
            - platform: nibe
              name: 'Climate System 1'
              system : 51460 # XXXXXXXX must be set to the actual system identifer
              current: 40033
              target : 47398 
              adjust : 47011
```

**Comment by iCarl** [comment]
Does climate require other dependencies?

**Comment by elupus** [comment]
The file structure that is in the repo is correct as it is.

No other dependencies.

**Comment by iCarl** [comment]
I get error `2018-06-25 22:30:26 ERROR (MainThread) [homeassistant.loader] Unable to find component climate.nibe` when I use the exact same configuration that you posted.
System shows up now, HUGE thanks for that:) But I'd like for climate to show as well

**Comment by elupus** [comment]
Climate is a hack at best. Not sure why you'd get that error.

**Comment by iCarl** [comment]
What could be the reason it isn't found?

**Comment by elupus** [comment]
What system is this installed on and what version home asssistant

**Comment by iCarl** [comment]
Raspberry Pi Manual install running version 0.72.1

**Comment by elupus** [comment]
Could you do a new install inside a virtualenv. Seems you didn't do that to begin with.

**Comment by elupus** [comment]
Would be nice if you could test the config on your normal computer. We have had problems with the python version on raspian.

**Comment by iCarl** [comment]
I did do the install inside a virtual enviroment.
I made a fresh install of Home Assistant yesterday and I am having the same issue as before.

**Comment by iCarl** [comment]
I just tried running it on MacOS and got the same exact error:

`2018-06-28 17:31:38 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_temperature: temperature=21.5, entity_id=['climate.nibe_51460_40033']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 339, in async_temperature_set_service
    await climate.async_set_temperature(**kwargs)
  File "/Users/carllarsson/.homeassistant/custom_components/climate/nibe.py", line 165, in async_set_temperature
    await self._uplink.set_parameter(self._system_id, self._target_id, data)
  File "/Users/carllarsson/.homeassistant/deps/lib/python/site-packages/nibeuplink/__init__.py", line 296, in set_parameter
    '{}/api/v1/systems/{}/parameters'.format(BASE_URL, system_id),
NameError: name 'BASE_URL' is not defined
`

**Comment by elupus** [comment]
In no way the exact same error. This error I can fix.

**Comment by iCarl** [comment]
How could I fix it?
I looked again and saw the errors weren't the same, sorry.
