### ISSUE TITLE
Passive cooling doesn't reflect status

### ISSUE THREAD

**Issue by Tommatheussen** [elupus/hass_nibe#70]
The passive cooling status is never reflected in HA. I've done some quick debugging myself as to why this happens. As explained in https://community.home-assistant.io/t/nibe-uplink-api-component/18173/488, there is a check which basically blocks this status from ever getting shown.

Passive cooling mode yields the following 3 results for my heat pump (F1245 PC), which I've quickly dumped in the logs straight from the code: 
```
{'Cooling (Passive)', 'Heating Medium Pump', 'Brine Pump'}
```
As you can see, Passive cooling actually uses the Heating pump (logical as it uses the same circuit).  As a result, the check at https://github.com/elupus/hass_nibe/blob/master/climate.py#L210 actually thinks it's in heating mode, as that's the first thing it finds and then just stops.

**Comment by elupus** [comment]
That seem should be ready to fix. Add check for passive cooling as first check. Can you provide a pull request?

**Comment by elupus** [comment]
Fixed.
