### ISSUE TITLE
How to find system identifier?

### ISSUE THREAD

**Issue by BloodyusHellus** [elupus/hass_nibe#75]
Followed instructions in readme, only added "nibe:" to config and added integration. No error message followed so where to find system identifier?

**Comment by elupus** [comment]
In the log.

**Comment by elupus** [comment]
Or in the notification on start if you have gone through config flow.

**Comment by BloodyusHellus** [comment]
Thanks for the quick reply, on restart I don't get a notification? Also no SystemID in home assistant log? Or do I need to check elsewhere?

**Comment by BloodyusHellus** [comment]
Also, what am I looking for? A string of numbers? For I do see "F1244-6 R PC - < 5 digit number >
Is that number the systemID?

**Comment by elupus** [comment]
No it's just 5 numbers. Login to nibeuplink.com and go to your system. If you look in the address bar of your browser the numbers will be there.

But you should be getting a notification in home assistant with it if you have finished linking your account.

**Comment by BloodyusHellus** [comment]
Okay thank you! These 5 numbers are indeed the same 5 numbers I saw in Home Assistant when viewing the device on the integrations page. No notification though, strange.
