### ISSUE TITLE
Only 2 devices and 4 entities showing up

### ISSUE THREAD

**Issue by davusk** [elupus/hass_nibe#77]
Hi,

Installed this addon and it seemed to work fine, but only 2 devices and 4 entities are showing up, do you possibly know what could cause this? So far I have tried the following:

* Reinstalling the addon multiple times, also using Git instead of HACS
* Removing/re-adding config to configuration.yaml
* Creating new Nibe API keys
* Upgraded Nibe software to latest version (9071R5) The model is a F470 R 3x400V NO
* Bought premium and added write access, did not really change much
* Did step 5 (adding more configuration) multiple times with multiple reboots

Devices discovered:
<address & system number > NIBE F470
Climate System S1 

Entities discovered:
water_heater.nibe_69679_40014_47387
climate.nibe_69679_s1_room
climate.nibe_69679_s1_supply
fan.nibe_69679_ventilation

**Comment by elupus** [comment]
These are the only default entities added. You need to enable categories in your config to get more stuff.

**Comment by davusk** [comment]
Thank you very much.

Works perfect now. 👍
