### ISSUE TITLE
Nibe Integration

### ISSUE THREAD

**Issue by papagooo** [elupus/hass_nibe#78]
Hi
Tried to get this Nibe Integration running on my HA but failed. Tried the installation method with HACS and custom repository. 
Going to the Integrations page located in Home Assistants Configuration dashboard I cannot see how to configure? see attachment
![nibe](https://user-images.githubusercontent.com/20760282/101207048-54179200-3670-11eb-9586-28122cfd960b.JPG)

**Comment by elupus** [comment]
You configure on the normal integrations page in standard settings.

Den fre 4 dec. 2020 20:37papagooo <notifications@github.com> skrev:

**Comment by JohnPhoto** [comment]
> You configure on the normal integrations page in standard settings.

With version 0.118.5 of HA I can not find the nibe-config in the the "normal integrations page".

**Comment by Adze1502** [comment]
After installation through HACS and restart of HASS AND clearing of browser cache (important), it is available to install on the normal integrations page in standard settings. Works for me.

**Comment by elupus** [comment]
You usually don't need to clear cache. But you may need to refresh the page so you trigger a new login.
