### ISSUE TITLE
slider option instead of switch

### ISSUE THREAD

**Issue by rickardnr1** [elupus/hass_nibe#79]
in some cases registers for exmple supply pump speed(43437) is possible to change between 0-100% . 
to add the register as switch dont work so how do i add the register so i can change it per percent?
(for this i also got writeaccsess)

**Comment by elupus** [comment]
This wasnt a possible entity type in home assistant until just recently. I think it might even be first in 1.0.0. 

I may add support when that is out.

**Comment by rickardnr1** [comment]
Looking forward to see the function. Keep up the great work!

**Comment by elupus** [comment]
Wait. This values are not changable. So there is no point in adding a slider for this. They should just be used as sensors. I will close this.
