### ISSUE TITLE
Error when starting up ha

### ISSUE THREAD

**Issue by greberg** [elupus/hass_nibe#8]
Hi

Using the latest repo and ha 0.74.2. At startup getting the below error. Doesn’t seem to affect but not sure. 

Homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nibe/__init__.py", line 111, in async_setup_systems
    await asyncio.gather(*tasks)
  File "/config/custom_components/nibe/__init__.py", line 373, in load
    await self.load_unit(unit)
  File "/config/custom_components/nibe/__init__.py", line 333, in load_unit
    unit.get(CONF_UNIT)))
  File "/config/custom_components/nibe/__init__.py", line 260, in load_status
    data = await self.uplink.get_status(self.system_id, unit)
TypeError: get_status() takes 2 positional arguments but 3 were given

**Comment by mrlook2** [comment]
I have the same issue

**Comment by elupus** [comment]
Just remove the "statuses" key in your config for now. I've not seen that return any data yet anyway. I'll fix it at some point.

**Comment by mrlook2** [comment]
I have this config now, but still the same error: 

nibe:
    client_id: <secret>
    client_secret: <secret>
    redirect_uri: http://127.0.0.1:8123
    systems:
        - system: <secret>
          
#          categories: # optional list of categories to retrieve, leave empty for all
          
#          statuses:   # optional list of status screens to retrieve, leave empty for all
           
#          parameters: # optional list of additional parameters to retrieve, can be done here or on the sensor platform

and getting this in the log:
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nibe.py", line 101, in async_setup_systems
    await asyncio.gather(*tasks)
  File "/home/homeassistant/.homeassistant/custom_components/nibe.py", line 210, in load
    group = loader.get_component('group')
TypeError: get_component() missing 1 required positional argument: 'comp_or_platform'

**Comment by mrlook2** [comment]
oh, categories, statuses and parameters is having # in front of them

**Comment by elupus** [comment]
@mrlook. Your config is invalid for latest version of the component (missing unit). Also, not the same error. Please update to latest version and reread the readme to correct your config.

**Comment by greberg** [comment]
Thanks! No error when removing statuses. Closing this as this full fills my issue that I reported and you are already aware of it. Please reopen if you want to have it as a reminder.

**Comment by elupus** [comment]
That's fine. Issue was fixed in https://github.com/elupus/hass_nibe/commit/8916e674c8af457a46ebaf3779c2ed94564fbe07
