### ISSUE TITLE
Support for different systems

### ISSUE THREAD

**Issue by NickSutton** [elupus/hass_nibe#85]
Hi there,

I have the F2040 heat pump system and got your integration up and running with no problems! 

I only have one entity reporting information (Heating water) and wondered whereabouts I should look in your files to add the parameters for other entities that are specific to my system? 

I appreciated you coded this for your own hardware, is there a way your HASS integration can be made more accessible by those of us with different Nibe heat pump models?

I tried, but failed, to get Postman to authenticate with the API so I could retrieve the parameters my heat pump makes available, so am now looking elsewhere for a list of parameters, in the hope I can tweak your code slightly to have access to more entities in HASS.

Cheers,
Nick

**Comment by dazmanic** [comment]
I've been playing around with both this integration and with the NibeUplink binding on openhab. I have an F370 exhaust air heat pump. In the openhab docs there's a list of the parameters, they call them Channel Type IDs. I just added the numbers of the ones I wanted as sensors, and even though they're not for my specific system, they work fine on my home assistant and show up with the name they have in NibeUplink. You only need the number as the parameter identifier, so for example BT1 Outdoor Temperature would be:

```
sensors:
  - 40004
```

Maybe it would be similar for you with your system?

https://www.openhab.org/addons/bindings/nibeuplink/

**Comment by NickSutton** [comment]
Cheers Daz, Knew I'd seen something somewhere. I'll have a go at updating the config with some values

**Comment by NickSutton** [comment]
So, I actually found that using the web inspector / dev tools built in to the browser to inspect elements of the data reported at nibeuplink website is the best way to go!

`        - 40004 #Outdoor temperature
        - 40014 # Hot water charging
        - 40013 # Hot water top
        - 40071 # External flow temp
        - 43009 # Calc flow Temp
        - 44058 # Supply temp
        - 44055 # Return Temp
        - 47011 # Heating Offset
        - 40121 # Heating Offset Temp
        - 44396 # Chargepump Speed
        - 44703 # Defrosting?
        - 47041 # Hot water mode: 0=Economy, 1=Normal, 2=Luxury
        - 48132 # Temporary Lux: 0=Off, 1=3h, 2=6h, 3=12h, 4=One time increase
        `

**Comment by dazmanic** [comment]
Good thinking. There's a couple of sensors on my system that aren't in the openhab docs, so that's useful to know. Thanks!

**Comment by NickSutton** [comment]
No drama.

Now I just need to work out what they all mean, what's good, what's bad etc 😂

**Comment by elupus** [comment]
Turn on categories setting. Then you get the same sensors you see in nibe uplink.

**Comment by NickSutton** [comment]
> Turn on categories setting. Then you get the same sensors you see in nibe uplink.

Didn't see that documented?
