### ISSUE TITLE
Home Assistant core-2021.3.2

### ISSUE THREAD

**Issue by oz9els** [elupus/hass_nibe#87]
First off, Joakim great job with this integration, it has been running smooooooth forever..
This is not an actual issue, just to reach out to others with similar problems.

After upgrading to core-2021.3.2, the integration did not present any values from the heater. restarted HA, restarted heater - still no values..
The fix was to disable and enable integration: 
Configuration->Integration->Nibe Uplink-> ...-> Disable
Configuration->Integration->Show disabled integrations->Nibe Uplink->Enable
 ;-) Easy peasy

**Comment by elupus** [comment]
Weirdness. I can't see any reason why that would help but.. okey :)
