### ISSUE TITLE
HA Automations for Nibe

### ISSUE THREAD

**Issue by NickSutton** [elupus/hass_nibe#89]
Hi all,

Not an issue, in fact installing this integration has been a breeze! I was wondering what you're all doing with the information? 

I don't know much about heat pumps. Is it energy saving to power one down if you're away from the house etc?

Is there any benefit to sending my Tado thermostat temps to the Nibe heat pump? 
I do have write access to the API, but, to be truthful, I have a Pi3 relaying data to/from my router (There's no way to get a cable to it) and I'm wondering if it's better to redeploy the Pi because all I'm seeing is numbers that don't make much sense and I'm coming up short on ideas of what to do with them!

Cheers

**Comment by elupus** [comment]
I'm mainly monitor behaviour. I also use thermostats using home assistant instead of hooked to the pump. But that is about it
