### ISSUE TITLE
Type checking HA code

### ISSUE THREAD

**Issue by KapJI** [elupus/hass_nibe#90]
HI!

I've seen your PR in HA: https://github.com/home-assistant/core/pull/28866

If you're still interesting in enabling these checks for your project, you might be interested in https://github.com/KapJI/homeassistant-stubs

Example how it can be used: https://github.com/leikoilja/ha-google-home
It actually contains a lot of good practices for testing the code, managing dependencies and releasing it through HACS.

**Comment by elupus** [comment]
I think it looks good idea. One thing that comes to mind is the namespacing of the pypi package. It ends up being close to the official packages in naming convention. Not sure I know a better name though :)

**Comment by KapJI** [comment]
Stubs packages must have name `<original package>-stubs` 🙂

**Comment by elupus** [comment]
I just did a pip install homeassistant-stubs in a testing repo of mine where i had an old homeassitant-dev version. It ended up upgrading homeassistant.

I wonder if there is some way to mark it so that it avoids upgrading existing libraries if an old version exist.

**Comment by KapJI** [comment]
I guess you need to specify which version of `homeassistant-stubs` you need to install. Its version should match HA Core version.
