### ISSUE TITLE
Virtual Thermostats created but not receiving temps

### ISSUE THREAD

**Issue by NickSutton** [elupus/hass_nibe#91]
Hi,

I finally got around to adding my thermostats to the nibe integration via the config file.
The thermostats have appeared in the Nibe MyUplink page, but are missing all the temperature data?

I've specified existing temp entities in my config, that are displaying values on the HA side of things. Any ideas?

Thanks
![Screenshot 2021-05-03 at 01 42 23](https://user-images.githubusercontent.com/24848258/116833402-d0c38380-abb0-11eb-8ad0-a83cf29eb7bb.png)

**Comment by elupus** [comment]
Select a mode

**Comment by NickSutton** [comment]
In HA, or Nibe? How do I do that please?

**Comment by NickSutton** [comment]
![Screenshot 2021-05-03 at 11 47 43](https://user-images.githubusercontent.com/24848258/116867592-61c44a00-ac05-11eb-9be2-216555818a93.png)

All I see is this, but the checkbox is disabled

**Comment by elupus** [comment]
In HA on the climate entity added.

**Comment by NickSutton** [comment]
Ok, I can see the new entities but still unclear on how to set the mode. Sorry if I've missed this somewhere!
