### ISSUE TITLE
Energy consumption sensors

### ISSUE THREAD

**Issue by elden1337** [elupus/hass_nibe#92]
Hi, thanks for this very useful integration. 

Are there plans to implement the energy consumption params as sensors, that at least f730 got last autumn?
I couldn't find them in the Nibe api-docs so perhaps it's a premature request if Nibe hasn't added them as exportable yet.

//Magnus

**Comment by elupus** [comment]
If they are available as service info they should show up. Otherwise if you know their oaramter numbers they might be possible to add manually.

**Comment by elden1337** [comment]
They are not yet available in the API. Spoke to a Nibe-tech. Closing issue for now.
