### ISSUE TITLE
Missing valid version key

### ISSUE THREAD

**Issue by ffsiim** [elupus/hass_nibe#94]
Hy, after upgrading to the latest HA release, the Nibe integration no longer loaded due to error: The custom integration 'nibe' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details.
Can you please look into it, love your integration.

**Comment by elupus** [comment]
Did you try upgrading the component? It has the version key since a while back.

**Comment by bjornwahman** [comment]
This worked for me, thank you elupus.
I added the nibe integration to my hacs now.

**Comment by saajs** [comment]
Hi elupus,
I have the same problem, however I don't understand what you mean by upgrade the component.
Could you explane?
Thanks in adavnce.

**Comment by elupus** [comment]
Rome it from custom_components and reinstall it. Possibly by hacs.

**Comment by saajs** [comment]
Great! Up & running again.
Thanks
