### ISSUE TITLE
Config flow setup and extra sensors

### ISSUE THREAD

**Issue by fondberg** [elupus/hass_nibe#95]
Is it possible to avoid yaml if I want to add extra sensors?
I just migrated away from yaml but I only have 2 devices and 5 entitites. I used to have > 30 entitites

**Comment by elupus** [comment]
Only in my dev branch i think. Don't think I added it to master. Not had much motivation to work on it lately.

**Comment by drivingmx** [comment]
did you set categories: true?

**Comment by elupus** [comment]
On new release, i default this to true. It's what everybody wants anyhow.
