### ISSUE TITLE
While Reinstalling manually - Config flow could not be loaded

### ISSUE THREAD

**Issue by hjallex** [elupus/hass_nibe#97]
Hi,
I was updating the core and the supervision and rebooted. the HA could't not found nibe any more so I was reinstalling the integration manually.

I have been edited my yalm file to "nibe:"
Then I go to integrations in HA I was searching for nibe and selected nibe, then I got the error:

Error
Config flow could not be loaded

I have tryed to restart HA, but it didn't work.

![Skärmklipp HA nibe setup intregration](https://user-images.githubusercontent.com/74986552/121260603-d304b600-c8b1-11eb-966c-21563a60017e.PNG)

**Comment by elupus** [comment]
You likely installed an old version of the component.

**Comment by hjallex** [comment]
I was downloading the files from here, were can I find the new files? :)

**Comment by elupus** [comment]
Then you must have managed to forget some files on install. I suggest you use hacs to install instead

**Comment by hjallex** [comment]
Now I have removed all old suffs with nibe and tryed to install nibe with hacs.
I was opening hacs, intregrations, pressed the 3 dots in the top of the right corner.
Addning the link to: https://github.com/elupus/hass_nibe.git 
Then I was restatarting HA and go to integrations in HA and search for Nibe, I got an hit, tryed to setup but I got the same fault.
I have also tryed to clean by browser histroy and cockies and open with "inkognitoflik". But it did't work.

Please help me :) !



![Skärmklipp Installing Nibe with HACS](https://user-images.githubusercontent.com/74986552/121348277-72fd2680-c928-11eb-9aac-64cf87e965fd.PNG)
![Skärmklipp HA hacs nibe](https://user-images.githubusercontent.com/74986552/121348300-7abccb00-c928-11eb-97e1-ab62bc629747.PNG)
![Skärmklipp nibe del 1](https://user-images.githubusercontent.com/74986552/121348356-8c9e6e00-c928-11eb-8ea7-281406516c4f.PNG)
![Skärmklipp HA nibe setup intregration](https://user-images.githubusercontent.com/74986552/121348372-958f3f80-c928-11eb-81e3-4412d9de45a8.PNG)

**Comment by elupus** [comment]
Check log for errors.

**Comment by hjallex** [comment]
Nothing with Nibe or Hacs?

![Skärmklipp Logg](https://user-images.githubusercontent.com/74986552/121363601-6502d200-c937-11eb-8451-ffaa08d84188.PNG)

**Comment by elupus** [comment]
Can you paste your full yaml config? (Remove secrets)

**Comment by hjallex** [comment]
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

ffmpeg:
        ffmpeg_bin: /usr/bin/ffmpeg



      


camera:
  - platform: generic
    name: Automower Location
    still_image_url: ???????????????????????????????????=YOURAPIKEY
    limit_refetch_to_url_change: true
       
       
       
hacs:
       token: ?????????????????????????????
  

      
      # Example configuration.yaml entry
feedreader:
  urls:
    - https://www.home-assistant.io/atom.xml
    - https://github.com/blog.atom
    - https://hasspodcast.io/feed/podcast
    - http://www.dn.se/nyheter/m/rss/
  scan_interval:
    minutes: 30
  max_entries: 5
    
# Example configuration.yaml entry
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
      
      
      
automower:
  username: !secret husqvarna_username
  password: !secret husqvarna_password
  
  
  
  
http:
 base_url: https:/??????????.duckdns.org
 ssl_certificate: /ssl/fullchain.pem
 ssl_key: /ssl/privkey.pem


 ???? = Hided information :)

**Comment by elupus** [comment]
Your

```
nibe:
```

section is missing?

**Comment by hjallex** [comment]
Yes. I have tested with and without "nibe:" but i get the same fault.
When I also reading the manual for installation with Hacs, it dont tells me to write "nibe:" in my yaml file. Mabye it does, but it is a litle bit confusing I think.

**Comment by elupus** [comment]
Have you setup an external/internal URL in home assistant?

**Comment by hjallex** [comment]
Yes, I have birthday, and flag days.

What do you think about it?

**Comment by elupus** [comment]
Eh??

**Comment by hjallex** [comment]
Sorry, the URLs is for a text file (RSS) with dates, with birthdays and flag days.
It is a reminder for me in the lovelace  :) like a magicmirror...

**Comment by elupus** [comment]
Eh?? What the heck are you talking about? Have you set up external and internal urls for your home assistant instance.

**Comment by hjallex** [comment]
I trought you was asking about my feedreader... What is wrong with my http ?

**Comment by elupus** [comment]
I'll ask again. For the third time. Have you configured the external/internal urls for your installation. This can be done in the gui.

**Comment by hjallex** [comment]
No, I do not have that because that is when the error message comes up. Then I'm stuck.
I'm sorry I did't not understand you.

**Comment by elupus** [comment]
This is settings for home assistant globally. Had nothing to do with nibe.

**Comment by hjallex** [comment]
Hi everyone!

Now I have found the fault!

IF you are not able to config the nibe module in intregrations, check you yalm code (<config dir>/configuration.yaml) and fix all you faults in the logg. **No fault in logg are allowed!**
If you want to run you Home Assistant remotley or localy and using https (https://homeassistant.local:8123) nibe setup will not work.
You need to remove you settings for https from yalm.
If you have this code: 
http:
 base_url: https://hiddeninformation.duckdns.org
 ssl_certificate: /ssl/fullchain.pem
 ssl_key: /ssl/privkey.pem

1. Remove it!

2. Now install nibe and follow the guide (https://github.com/elupus/hass_nibe)

3. - Don't forget to add "**nibe:**" in the yalm.

4. - Setup the integration nibe in HA

5. - Restart and add the following code for nibe in yalm:

 **nibe:
  systems:
    - system: <required system identifier>
      units:
        - unit: 0)**

6. - Restart HA


7. Then when you se the module working correctley, then you can add you **http** code in yalm again. 
**And nibe will work to full!!**

God luck everyone :)

**Comment by elupus** [comment]
Well base_url is deprecated.. and should not be used. You should setup external/internal addresses in gui like I've said many times now.

**Comment by hjallex** [comment]
Okey elupus. I can move my base_url or remove it, but where can I found gui? Are you able to give me a screenshot so I can understand how you realy mean?

**Comment by elupus** [comment]
First link googling home assistant external url: https://www.home-assistant.io/docs/configuration/basic/

**Comment by hjallex** [comment]
I have removed the base_url from yalm now, and add that lite to external url i HA, and i seems to work.
Thank you for the advice!

**Comment by hjallex** [comment]
Do you also have any solution about this to? :)

![Skärmklipp Nibe Log](https://user-images.githubusercontent.com/74986552/121928957-fcee2a80-cd40-11eb-9d69-9dca88819e11.PNG)

**Comment by elupus** [comment]
Do as instructed,.read readme about config.
